from Move import Move
MovesList = {
    "pound": Move("pound", "normal", "physical", 40, 1.0, 35, None),
    "karate chop": Move("karate chop", "fighting", "physical", 50, 1.0, 25, None),
    "double slap": Move("double slap", "normal", "physical", 15, 0.85, 10, None),
    "comet punch": Move("comet punch", "normal", "physical", 18, 0.85, 15, None),
    "mega punch": Move("mega punch", "normal", "physical", 80, 0.85, 20, None),
    "pay day": Move("pay day", "normal", "physical", 40, 1.0, 20, None),
    "fire punch": Move("fire punch", "fire", "physical", 75, 1.0, 15, None),
    "ice punch": Move("ice punch", "ice", "physical", 75, 1.0, 15, None),
    "thunder punch": Move("thunder punch", "electric", "physical", 75, 1.0, 15, None),
    "scratch": Move("scratch", "normal", "physical", 40, 1.0, 35, None),
    "vice grip": Move("vice grip", "normal", "physical", 55, 1.0, 30, None),
    "guillotine": Move("guillotine", "normal", "physical", None, 0.3, 5, None),
    "razor wind": Move("razor wind", "normal", "special", 80, 1.0, 10, None),
    "swords dance": Move("swords dance", "normal", "status", None, None, 20, {"target_stat": ["self", "attack"], "change": [+2]}),
    "cut": Move("cut", "normal", "physical", 50, 0.95, 30, None),
    "gust": Move("gust", "flying", "special", 40, 1.0, 35, None),
    "wing attack": Move("wing attack", "flying", "physical", 60, 1.0, 35, None),
    "whirlwind": Move("whirlwind", "normal", "status", None, None, 20, None),
    "fly": Move("fly", "flying", "physical", 90, 0.95, 15, None),
    "bind": Move("bind", "normal", "physical", 15, 0.85, 20, None),
    "slam": Move("slam", "normal", "physical", 80, 0.75, 20, None),
    "vine whip": Move("vine whip", "grass", "physical", 45, 1.0, 25, None),
    "stomp": Move("stomp", "normal", "physical", 65, 1.0, 20, None),
    "double kick": Move("double kick", "fighting", "physical", 30, 1.0, 30, None),
    "mega kick": Move("mega kick", "normal", "physical", 120, 0.75, 5, None),
    "jump kick": Move("jump kick", "fighting", "physical", 100, 0.95, 10, None),
    "rolling kick": Move("rolling kick", "fighting", "physical", 60, 0.85, 15, None),
    "sand attack": Move("sand attack", "ground", "status", None, 1.0, 15, {"target_stat": ["opponent", "accuracy"], "change": [-1]}),
    "headbutt": Move("headbutt", "normal", "physical", 70, 1.0, 15, None),
    "horn attack": Move("horn attack", "normal", "physical", 65, 1.0, 25, None),
    "fury attack": Move("fury attack", "normal", "physical", 15, 0.85, 20, None),
    "horn drill": Move("horn drill", "normal", "physical", None, 0.3, 5, None),
    "tackle": Move("tackle", "normal", "physical", 40, 1.0, 35, None),
    "body slam": Move("body slam", "normal", "physical", 85, 1.0, 15, None),
    "wrap": Move("wrap", "normal", "physical", 15, 0.9, 20, None),
    "take down": Move("take down", "normal", "physical", 90, 0.85, 20, None),
    "thrash": Move("thrash", "normal", "physical", 120, 1.0, 10, None),
    "double edge": Move("double edge", "normal", "physical", 120, 1.0, 15, None),
    "tail whip": Move("tail whip", "normal", "status", None, 1.0, 30, {"target_stat": ["opponent", "defense"], "change": [-1]}),
    "poison sting": Move("poison sting", "poison", "physical", 15, 1.0, 35, None),
    "twineedle": Move("twineedle", "bug", "physical", 25, 1.0, 20, None),
    "pin missile": Move("pin missile", "bug", "physical", 25, 0.95, 20, None),
    "leer": Move("leer", "normal", "status", None, 1.0, 30, {"target_stat": ["opponent", "defense"], "change": [-1]}),
    "bite": Move("bite", "dark", "physical", 60, 1.0, 25, None),
    "growl": Move("growl", "normal", "status", None, 1.0, 40, {"target_stat": ["opponent", "attack"], "change": [-1]}),
    "roar": Move("roar", "normal", "status", None, None, 20, None),
    "sing": Move("sing", "normal", "status", None, 0.55, 15, None),
    "supersonic": Move("supersonic", "normal", "status", None, 0.55, 20, None),
    "sonic boom": Move("sonic boom", "normal", "special", None, 0.9, 20, None),
    "disable": Move("disable", "normal", "status", None, 1.0, 20, None),
    "acid": Move("acid", "poison", "special", 40, 1.0, 30, {"target_stat": ["opponent", "special_defense"], "change": [-1]}),
    "ember": Move("ember", "fire", "special", 40, 1.0, 25, None),
    "flamethrower": Move("flamethrower", "fire", "special", 90, 1.0, 15, None),
    "mist": Move("mist", "ice", "status", None, None, 30, None),
    "water gun": Move("water gun", "water", "special", 40, 1.0, 25, None),
    "hydro pump": Move("hydro pump", "water", "special", 110, 0.8, 5, None),
    "surf": Move("surf", "water", "special", 90, 1.0, 15, None),
    "ice beam": Move("ice beam", "ice", "special", 90, 1.0, 10, None),
    "blizzard": Move("blizzard", "ice", "special", 110, 0.7, 5, None),
    "psybeam": Move("psybeam", "psychic", "special", 65, 1.0, 20, None),
    "bubble beam": Move("bubble beam", "water", "special", 65, 1.0, 20, {"target_stat": ["opponent", "speed"], "change": [-1]}),
    "aurora beam": Move("aurora beam", "ice", "special", 65, 1.0, 20, {"target_stat": ["opponent", "attack"], "change": [-1]}),
    "hyper beam": Move("hyper beam", "normal", "special", 150, 0.9, 5, None),
    "peck": Move("peck", "flying", "physical", 35, 1.0, 35, None),
    "drill peck": Move("drill peck", "flying", "physical", 80, 1.0, 20, None),
    "submission": Move("submission", "fighting", "physical", 80, 0.8, 20, None),
    "low kick": Move("low kick", "fighting", "physical", None, 1.0, 20, None),
    "counter": Move("counter", "fighting", "physical", None, 1.0, 20, None),
    "seismic toss": Move("seismic toss", "fighting", "physical", None, 1.0, 20, None),
    "strength": Move("strength", "normal", "physical", 80, 1.0, 15, None),
    "absorb": Move("absorb", "grass", "special", 20, 1.0, 25, None),
    "mega drain": Move("mega drain", "grass", "special", 40, 1.0, 15, None),
    "leech seed": Move("leech seed", "grass", "status", None, 0.9, 10, None),
    "growth": Move("growth", "normal", "status", None, None, 20, {"target_stat": ["self", "attack", "special_attack"], "change": [+1, +1]}),
    "razor leaf": Move("razor leaf", "grass", "physical", 55, 0.95, 25, None),
    "solar beam": Move("solar beam", "grass", "special", 120, 1.0, 10, None),
    "poison powder": Move("poison powder", "poison", "status", None, 0.75, 35, None),
    "stun spore": Move("stun spore", "grass", "status", None, 0.75, 30, None),
    "sleep powder": Move("sleep powder", "grass", "status", None, 0.75, 15, None),
    "petal dance": Move("petal dance", "grass", "special", 120, 1.0, 10, None),
    "string shot": Move("string shot", "bug", "status", None, 0.95, 40, {"target_stat": ["opponent", "speed"], "change": [-2]}),
    "dragon rage": Move("dragon rage", "dragon", "special", None, 1.0, 10, None),
    "fire spin": Move("fire spin", "fire", "special", 35, 0.85, 15, None),
    "thunder shock": Move("thunder shock", "electric", "special", 40, 1.0, 30, None),
    "thunderbolt": Move("thunderbolt", "electric", "special", 90, 1.0, 15, None),
    "thunder wave": Move("thunder wave", "electric", "status", None, 0.9, 20, None),
    "thunder": Move("thunder", "electric", "special", 110, 0.7, 10, None),
    "rock throw": Move("rock throw", "rock", "physical", 50, 0.9, 15, None),
    "earthquake": Move("earthquake", "ground", "physical", 100, 1.0, 10, None),
    "fissure": Move("fissure", "ground", "physical", None, 0.3, 5, None),
    "dig": Move("dig", "ground", "physical", 80, 1.0, 10, None),
    "toxic": Move("toxic", "poison", "status", None, 0.9, 10, None),
    "confusion": Move("confusion", "psychic", "special", 50, 1.0, 25, None),
    "psychic": Move("psychic", "psychic", "special", 90, 1.0, 10, {"target_stat": ["opponent", "special_defense"], "change": [-1]}),
    "hypnosis": Move("hypnosis", "psychic", "status", None, 0.6, 20, None),
    "meditate": Move("meditate", "psychic", "status", None, None, 40, {"target_stat": ["self", "attack"], "change": [+1]}),
    "agility": Move("agility", "psychic", "status", None, None, 30, {"target_stat": ["self", "speed"], "change": [+2]}),
    "quick attack": Move("quick attack", "normal", "physical", 40, 1.0, 30, None),
    "rage": Move("rage", "normal", "physical", 20, 1.0, 20, None),
    "teleport": Move("teleport", "psychic", "status", None, None, 20, None),
    "night shade": Move("night shade", "ghost", "special", None, 1.0, 15, None),
    "mimic": Move("mimic", "normal", "status", None, None, 10, None),
    "screech": Move("screech", "normal", "status", None, 0.85, 40, {"target_stat": ["opponent", "defense"], "change": [-2]}),
    "double team": Move("double team", "normal", "status", None, None, 15, {"target_stat": ["self", "evasion"], "change": [+1]}),
    "recover": Move("recover", "normal", "status", None, None, 5, None),
    "harden": Move("harden", "normal", "status", None, None, 30, {"target_stat": ["self", "defense"], "change": [+1]}),
    "minimize": Move("minimize", "normal", "status", None, None, 10, {"target_stat": ["self", "evasion"], "change": [+2]}),
    "smokescreen": Move("smokescreen", "normal", "status", None, 1.0, 20, {"target_stat": ["opponent", "accuracy"], "change": [-1]}),
    "confuse ray": Move("confuse ray", "ghost", "status", None, 1.0, 10, None),
    "withdraw": Move("withdraw", "water", "status", None, None, 40, {"target_stat": ["self", "defense"], "change": [+1]}),
    "defense curl": Move("defense curl", "normal", "status", None, None, 40, {"target_stat": ["self", "defense"], "change": [+1]}),
    "barrier": Move("barrier", "psychic", "status", None, None, 20, {"target_stat": ["self", "defense"], "change": [+2]}),
    "light screen": Move("light screen", "psychic", "status", None, None, 30, None),
    "haze": Move("haze", "ice", "status", None, None, 30, None),
    "reflect": Move("reflect", "psychic", "status", None, None, 20, None),
    "focus energy": Move("focus energy", "normal", "status", None, None, 30, None),
    "bide": Move("bide", "normal", "physical", None, None, 10, None),
    "metronome": Move("metronome", "normal", "status", None, None, 10, None),
    "mirror move": Move("mirror move", "flying", "status", None, None, 20, None),
    "self destruct": Move("self destruct", "normal", "physical", 200, 1.0, 5, None),
    "egg bomb": Move("egg bomb", "normal", "physical", 100, 0.75, 10, None),
    "lick": Move("lick", "ghost", "physical", 30, 1.0, 30, None),
    "smog": Move("smog", "poison", "special", 30, 0.7, 20, None),
    "sludge": Move("sludge", "poison", "special", 65, 1.0, 20, None),
    "bone club": Move("bone club", "ground", "physical", 65, 0.85, 20, None),
    "fire blast": Move("fire blast", "fire", "special", 110, 0.85, 5, None),
    "waterfall": Move("waterfall", "water", "physical", 80, 1.0, 15, None),
    "clamp": Move("clamp", "water", "physical", 35, 0.85, 15, None),
    "swift": Move("swift", "normal", "special", 60, None, 20, None),
    "skull bash": Move("skull bash", "normal", "physical", 130, 1.0, 10, None),
    "spike cannon": Move("spike cannon", "normal", "physical", 20, 1.0, 15, None),
    "constrict": Move("constrict", "normal", "physical", 10, 1.0, 35, {"target_stat": ["opponent", "speed"], "change": [-1]}),
    "amnesia": Move("amnesia", "psychic", "status", None, None, 20, {"target_stat": ["self", "special_defense"], "change": [+2]}),
    "kinesis": Move("kinesis", "psychic", "status", None, 0.8, 15, {"target_stat": ["opponent", "accuracy"], "change": [-1]}),
    "soft boiled": Move("soft boiled", "normal", "status", None, None, 5, None),
    "high jump kick": Move("high jump kick", "fighting", "physical", 130, 0.9, 10, None),
    "glare": Move("glare", "normal", "status", None, 1.0, 30, None),
    "dream eater": Move("dream eater", "psychic", "special", 100, 1.0, 15, None),
    "poison gas": Move("poison gas", "poison", "status", None, 0.9, 40, None),
    "barrage": Move("barrage", "normal", "physical", 15, 0.85, 20, None),
    "leech life": Move("leech life", "bug", "physical", 80, 1.0, 10, None),
    "lovely kiss": Move("lovely kiss", "normal", "status", None, 0.75, 10, None),
    "sky attack": Move("sky attack", "flying", "physical", 140, 0.9, 5, None),
    "transform": Move("transform", "normal", "status", None, None, 10, None),
    "bubble": Move("bubble", "water", "special", 40, 1.0, 30, {"target_stat": ["opponent", "speed"], "change": [-1]}),
    "dizzy punch": Move("dizzy punch", "normal", "physical", 70, 1.0, 10, None),
    "spore": Move("spore", "grass", "status", None, 1.0, 15, None),
    "flash": Move("flash", "normal", "status", None, 1.0, 20, {"target_stat": ["opponent", "accuracy"], "change": [-1]}),
    "psywave": Move("psywave", "psychic", "special", None, 1.0, 15, None),
    "splash": Move("splash", "normal", "status", None, None, 40, None),
    "acid armor": Move("acid armor", "poison", "status", None, None, 20, {"target_stat": ["self", "defense"], "change": [+2]}),
    "crabhammer": Move("crabhammer", "water", "physical", 100, 0.9, 10, None),
    "explosion": Move("explosion", "normal", "physical", 250, 1.0, 5, None),
    "fury swipes": Move("fury swipes", "normal", "physical", 18, 0.8, 15, None),
    "bonemerang": Move("bonemerang", "ground", "physical", 50, 0.9, 10, None),
    "rest": Move("rest", "psychic", "status", None, None, 5, None),
    "rock slide": Move("rock slide", "rock", "physical", 75, 0.9, 10, None),
    "hyper fang": Move("hyper fang", "normal", "physical", 80, 0.9, 15, None),
    "sharpen": Move("sharpen", "normal", "status", None, None, 30, {"target_stat": ["self", "attack"], "change": [+1]}),
    "conversion": Move("conversion", "normal", "status", None, None, 30, None),
    "tri attack": Move("tri attack", "normal", "special", 80, 1.0, 10, None),
    "super fang": Move("super fang", "normal", "physical", None, 0.9, 10, None),
    "slash": Move("slash", "normal", "physical", 70, 1.0, 20, None),
    "substitute": Move("substitute", "normal", "status", None, None, 10, None),
    "struggle": Move("struggle", "normal", "physical", 50, None, 1, None),
}
