
class Move:
    def __init__(self, name, move_type, category, power, accuracy, pp, effect):
        self.name = name
        self.type = move_type
        self.category = category
        self.power = power
        self.accuracy = accuracy
        self.pp = pp
        self.effect = effect

    def move_copy(self):
        return Move(
            self.name,
            self.type,
            self.category,
            self.power,
            self.accuracy,
            self.pp,
            effect=self.effect.copy() if self.effect else None
        )


MovesList = {
    "pound": Move("pound", "normal", "physical", 40, 1.0, 35, None),
    "karate chop": Move("karate chop", "fighting", "physical", 50, 1.0, 25, None),
    "double slap": Move("double slap", "normal", "physical", 15, 0.85, 10, None),
    "comet punch": Move("comet punch", "normal", "physical", 18, 0.85, 15, None),
    "mega punch": Move("mega punch", "normal", "physical", 80, 0.85, 20, None),
    "pay day": Move("pay day", "normal", "physical", 40, 1.0, 20, None),
    "fire punch": Move("fire punch", "fire", "physical", 75, 1.0, 15, None),
    "ice punch": Move("ice punch", "ice", "physical", 75, 1.0, 15, None),
    "thunder punch": Move("thunder punch", "electric", "physical", 75, 1.0, 15, None),
    "scratch": Move("scratch", "normal", "physical", 40, 1.0, 35, None),
    "vice grip": Move("vice grip", "normal", "physical", 55, 1.0, 30, None),
    "guillotine": Move("guillotine", "normal", "physical", None, 0.3, 5, None),
    "razor wind": Move("razor wind", "normal", "special", 80, 1.0, 10, None),
    "swords dance": Move("swords dance", "normal", "status", None, None, 20, {"target_stat": ["self", "attack"], "change": [+2]}),
    "cut": Move("cut", "normal", "physical", 50, 0.95, 30, None),
    "gust": Move("gust", "flying", "special", 40, 1.0, 35, None),
    "wing attack": Move("wing attack", "flying", "physical", 60, 1.0, 35, None),
    "whirlwind": Move("whirlwind", "normal", "status", None, None, 20, None),
    "fly": Move("fly", "flying", "physical", 90, 0.95, 15, None),
    "bind": Move("bind", "normal", "physical", 15, 0.85, 20, None),
    "slam": Move("slam", "normal", "physical", 80, 0.75, 20, None),
    "vine whip": Move("vine whip", "grass", "physical", 45, 1.0, 25, None),
    "stomp": Move("stomp", "normal", "physical", 65, 1.0, 20, None),
    "double kick": Move("double kick", "fighting", "physical", 30, 1.0, 30, None),
    "mega kick": Move("mega kick", "normal", "physical", 120, 0.75, 5, None),
    "jump kick": Move("jump kick", "fighting", "physical", 100, 0.95, 10, None),
    "rolling kick": Move("rolling kick", "fighting", "physical", 60, 0.85, 15, None),
    "sand attack": Move("sand attack", "ground", "status", None, 1.0, 15, {"target_stat": ["opponent", "accuracy"], "change": [-1]}),
    "headbutt": Move("headbutt", "normal", "physical", 70, 1.0, 15, None),
    "horn attack": Move("horn attack", "normal", "physical", 65, 1.0, 25, None),
    "fury attack": Move("fury attack", "normal", "physical", 15, 0.85, 20, None),
    "horn drill": Move("horn drill", "normal", "physical", None, 0.3, 5, None),
    "tackle": Move("tackle", "normal", "physical", 40, 1.0, 35, None),
    "body slam": Move("body slam", "normal", "physical", 85, 1.0, 15, None),
    "wrap": Move("wrap", "normal", "physical", 15, 0.9, 20, None),
    "take down": Move("take down", "normal", "physical", 90, 0.85, 20, None),
    "thrash": Move("thrash", "normal", "physical", 120, 1.0, 10, None),
    "double edge": Move("double edge", "normal", "physical", 120, 1.0, 15, None),
    "tail whip": Move("tail whip", "normal", "status", None, 1.0, 30, {"target_stat": ["opponent", "defense"], "change": [-1]}),
    "poison sting": Move("poison sting", "poison", "physical", 15, 1.0, 35, None),
    "twineedle": Move("twineedle", "bug", "physical", 25, 1.0, 20, None),
    "pin missile": Move("pin missile", "bug", "physical", 25, 0.95, 20, None),
    "leer": Move("leer", "normal", "status", None, 1.0, 30, {"target_stat": ["opponent", "defense"], "change": [-1]}),
    "bite": Move("bite", "dark", "physical", 60, 1.0, 25, None),
    "growl": Move("growl", "normal", "status", None, 1.0, 40, {"target_stat": ["opponent", "attack"], "change": [-1]}),
    "roar": Move("roar", "normal", "status", None, None, 20, None),
    "sing": Move("sing", "normal", "status", None, 0.55, 15, None),
    "supersonic": Move("supersonic", "normal", "status", None, 0.55, 20, None),
    "sonic boom": Move("sonic boom", "normal", "special", None, 0.9, 20, None),
    "disable": Move("disable", "normal", "status", None, 1.0, 20, None),
    "acid": Move("acid", "poison", "special", 40, 1.0, 30, {"target_stat": ["opponent", "special_defense"], "change": [-1]}),
    "ember": Move("ember", "fire", "special", 40, 1.0, 25, None),
    "flamethrower": Move("flamethrower", "fire", "special", 90, 1.0, 15, None),
    "mist": Move("mist", "ice", "status", None, None, 30, None),
    "water gun": Move("water gun", "water", "special", 40, 1.0, 25, None),
    "hydro pump": Move("hydro pump", "water", "special", 110, 0.8, 5, None),
    "surf": Move("surf", "water", "special", 90, 1.0, 15, None),
    "ice beam": Move("ice beam", "ice", "special", 90, 1.0, 10, None),
    "blizzard": Move("blizzard", "ice", "special", 110, 0.7, 5, None),
    "psybeam": Move("psybeam", "psychic", "special", 65, 1.0, 20, None),
    "bubble beam": Move("bubble beam", "water", "special", 65, 1.0, 20, {"target_stat": ["opponent", "speed"], "change": [-1]}),
    "aurora beam": Move("aurora beam", "ice", "special", 65, 1.0, 20, {"target_stat": ["opponent", "attack"], "change": [-1]}),
    "hyper beam": Move("hyper beam", "normal", "special", 150, 0.9, 5, None),
    "peck": Move("peck", "flying", "physical", 35, 1.0, 35, None),
    "drill peck": Move("drill peck", "flying", "physical", 80, 1.0, 20, None),
    "submission": Move("submission", "fighting", "physical", 80, 0.8, 20, None),
    "low kick": Move("low kick", "fighting", "physical", None, 1.0, 20, None),
    "counter": Move("counter", "fighting", "physical", None, 1.0, 20, None),
    "seismic toss": Move("seismic toss", "fighting", "physical", None, 1.0, 20, None),
    "strength": Move("strength", "normal", "physical", 80, 1.0, 15, None),
    "absorb": Move("absorb", "grass", "special", 20, 1.0, 25, None),
    "mega drain": Move("mega drain", "grass", "special", 40, 1.0, 15, None),
    "leech seed": Move("leech seed", "grass", "status", None, 0.9, 10, None),
    "growth": Move("growth", "normal", "status", None, None, 20, {"target_stat": ["self", "attack", "special_attack"], "change": [+1, +1]}),
    "razor leaf": Move("razor leaf", "grass", "physical", 55, 0.95, 25, None),
    "solar beam": Move("solar beam", "grass", "special", 120, 1.0, 10, None),
    "poison powder": Move("poison powder", "poison", "status", None, 0.75, 35, None),
    "stun spore": Move("stun spore", "grass", "status", None, 0.75, 30, None),
    "sleep powder": Move("sleep powder", "grass", "status", None, 0.75, 15, None),
    "petal dance": Move("petal dance", "grass", "special", 120, 1.0, 10, None),
    "string shot": Move("string shot", "bug", "status", None, 0.95, 40, {"target_stat": ["opponent", "speed"], "change": [-2]}),
    "dragon rage": Move("dragon rage", "dragon", "special", None, 1.0, 10, None),
    "fire spin": Move("fire spin", "fire", "special", 35, 0.85, 15, None),
    "thunder shock": Move("thunder shock", "electric", "special", 40, 1.0, 30, None),
    "thunderbolt": Move("thunderbolt", "electric", "special", 90, 1.0, 15, None),
    "thunder wave": Move("thunder wave", "electric", "status", None, 0.9, 20, None),
    "thunder": Move("thunder", "electric", "special", 110, 0.7, 10, None),
    "rock throw": Move("rock throw", "rock", "physical", 50, 0.9, 15, None),
    "earthquake": Move("earthquake", "ground", "physical", 100, 1.0, 10, None),
    "fissure": Move("fissure", "ground", "physical", None, 0.3, 5, None),
    "dig": Move("dig", "ground", "physical", 80, 1.0, 10, None),
    "toxic": Move("toxic", "poison", "status", None, 0.9, 10, None),
    "confusion": Move("confusion", "psychic", "special", 50, 1.0, 25, None),
    "psychic": Move("psychic", "psychic", "special", 90, 1.0, 10, {"target_stat": ["opponent", "special_defense"], "change": [-1]}),
    "hypnosis": Move("hypnosis", "psychic", "status", None, 0.6, 20, None),
    "meditate": Move("meditate", "psychic", "status", None, None, 40, {"target_stat": ["self", "attack"], "change": [+1]}),
    "agility": Move("agility", "psychic", "status", None, None, 30, {"target_stat": ["self", "speed"], "change": [+2]}),
    "quick attack": Move("quick attack", "normal", "physical", 40, 1.0, 30, None),
    "rage": Move("rage", "normal", "physical", 20, 1.0, 20, None),
    "teleport": Move("teleport", "psychic", "status", None, None, 20, None),
    "night shade": Move("night shade", "ghost", "special", None, 1.0, 15, None),
    "mimic": Move("mimic", "normal", "status", None, None, 10, None),
    "screech": Move("screech", "normal", "status", None, 0.85, 40, {"target_stat": ["opponent", "defense"], "change": [-2]}),
    "double team": Move("double team", "normal", "status", None, None, 15, {"target_stat": ["self", "evasion"], "change": [+1]}),
    "recover": Move("recover", "normal", "status", None, None, 5, None),
    "harden": Move("harden", "normal", "status", None, None, 30, {"target_stat": ["self", "defense"], "change": [+1]}),
    "minimize": Move("minimize", "normal", "status", None, None, 10, {"target_stat": ["self", "evasion"], "change": [+2]}),
    "smokescreen": Move("smokescreen", "normal", "status", None, 1.0, 20, {"target_stat": ["opponent", "accuracy"], "change": [-1]}),
    "confuse ray": Move("confuse ray", "ghost", "status", None, 1.0, 10, None),
    "withdraw": Move("withdraw", "water", "status", None, None, 40, {"target_stat": ["self", "defense"], "change": [+1]}),
    "defense curl": Move("defense curl", "normal", "status", None, None, 40, {"target_stat": ["self", "defense"], "change": [+1]}),
    "barrier": Move("barrier", "psychic", "status", None, None, 20, {"target_stat": ["self", "defense"], "change": [+2]}),
    "light screen": Move("light screen", "psychic", "status", None, None, 30, None),
    "haze": Move("haze", "ice", "status", None, None, 30, None),
    "reflect": Move("reflect", "psychic", "status", None, None, 20, None),
    "focus energy": Move("focus energy", "normal", "status", None, None, 30, None),
    "bide": Move("bide", "normal", "physical", None, None, 10, None),
    "metronome": Move("metronome", "normal", "status", None, None, 10, None),
    "mirror move": Move("mirror move", "flying", "status", None, None, 20, None),
    "self destruct": Move("self destruct", "normal", "physical", 200, 1.0, 5, None),
    "egg bomb": Move("egg bomb", "normal", "physical", 100, 0.75, 10, None),
    "lick": Move("lick", "ghost", "physical", 30, 1.0, 30, None),
    "smog": Move("smog", "poison", "special", 30, 0.7, 20, None),
    "sludge": Move("sludge", "poison", "special", 65, 1.0, 20, None),
    "bone club": Move("bone club", "ground", "physical", 65, 0.85, 20, None),
    "fire blast": Move("fire blast", "fire", "special", 110, 0.85, 5, None),
    "waterfall": Move("waterfall", "water", "physical", 80, 1.0, 15, None),
    "clamp": Move("clamp", "water", "physical", 35, 0.85, 15, None),
    "swift": Move("swift", "normal", "special", 60, None, 20, None),
    "skull bash": Move("skull bash", "normal", "physical", 130, 1.0, 10, None),
    "spike cannon": Move("spike cannon", "normal", "physical", 20, 1.0, 15, None),
    "constrict": Move("constrict", "normal", "physical", 10, 1.0, 35, {"target_stat": ["opponent", "speed"], "change": [-1]}),
    "amnesia": Move("amnesia", "psychic", "status", None, None, 20, {"target_stat": ["self", "special_defense"], "change": [+2]}),
    "kinesis": Move("kinesis", "psychic", "status", None, 0.8, 15, {"target_stat": ["opponent", "accuracy"], "change": [-1]}),
    "soft boiled": Move("soft boiled", "normal", "status", None, None, 5, None),
    "high jump kick": Move("high jump kick", "fighting", "physical", 130, 0.9, 10, None),
    "glare": Move("glare", "normal", "status", None, 1.0, 30, None),
    "dream eater": Move("dream eater", "psychic", "special", 100, 1.0, 15, None),
    "poison gas": Move("poison gas", "poison", "status", None, 0.9, 40, None),
    "barrage": Move("barrage", "normal", "physical", 15, 0.85, 20, None),
    "leech life": Move("leech life", "bug", "physical", 80, 1.0, 10, None),
    "lovely kiss": Move("lovely kiss", "normal", "status", None, 0.75, 10, None),
    "sky attack": Move("sky attack", "flying", "physical", 140, 0.9, 5, None),
    "transform": Move("transform", "normal", "status", None, None, 10, None),
    "bubble": Move("bubble", "water", "special", 40, 1.0, 30, {"target_stat": ["opponent", "speed"], "change": [-1]}),
    "dizzy punch": Move("dizzy punch", "normal", "physical", 70, 1.0, 10, None),
    "spore": Move("spore", "grass", "status", None, 1.0, 15, None),
    "flash": Move("flash", "normal", "status", None, 1.0, 20, {"target_stat": ["opponent", "accuracy"], "change": [-1]}),
    "psywave": Move("psywave", "psychic", "special", None, 1.0, 15, None),
    "splash": Move("splash", "normal", "status", None, None, 40, None),
    "acid armor": Move("acid armor", "poison", "status", None, None, 20, {"target_stat": ["self", "defense"], "change": [+2]}),
    "crabhammer": Move("crabhammer", "water", "physical", 100, 0.9, 10, None),
    "explosion": Move("explosion", "normal", "physical", 250, 1.0, 5, None),
    "fury swipes": Move("fury swipes", "normal", "physical", 18, 0.8, 15, None),
    "bonemerang": Move("bonemerang", "ground", "physical", 50, 0.9, 10, None),
    "rest": Move("rest", "psychic", "status", None, None, 5, None),
    "rock slide": Move("rock slide", "rock", "physical", 75, 0.9, 10, None),
    "hyper fang": Move("hyper fang", "normal", "physical", 80, 0.9, 15, None),
    "sharpen": Move("sharpen", "normal", "status", None, None, 30, {"target_stat": ["self", "attack"], "change": [+1]}),
    "conversion": Move("conversion", "normal", "status", None, None, 30, None),
    "tri attack": Move("tri attack", "normal", "special", 80, 1.0, 10, None),
    "super fang": Move("super fang", "normal", "physical", None, 0.9, 10, None),
    "slash": Move("slash", "normal", "physical", 70, 1.0, 20, None),
    "substitute": Move("substitute", "normal", "status", None, None, 10, None),
    "struggle": Move("struggle", "normal", "physical", 50, None, 1, None),
    "sketch": Move("sketch", "normal", "status", None, None, 1, None),
    "triple kick": Move("triple kick", "fighting", "physical", 10, 0.9, 10, None),
    "thief": Move("thief", "dark", "physical", 60, 1.0, 25, None),
    "spider web": Move("spider web", "bug", "status", None, None, 10, None),
    "mind reader": Move("mind reader", "normal", "status", None, None, 5, None),
    "nightmare": Move("nightmare", "ghost", "status", None, 1.0, 15, None),
    "flame wheel": Move("flame wheel", "fire", "physical", 60, 1.0, 25, None),
    "snore": Move("snore", "normal", "special", 50, 1.0, 15, None),
    "curse": Move("curse", "ghost", "status", None, None, 10, None),
    "flail": Move("flail", "normal", "physical", None, 1.0, 15, None),
    "conversion 2": Move("conversion 2", "normal", "status", None, None, 30, None),
    "aeroblast": Move("aeroblast", "flying", "special", 100, 0.95, 5, None),
    "cotton spore": Move("cotton spore", "grass", "status", None, 1.0, 40, {"target_stat": ["opponent", "speed"], "change": [-2]}),
    "reversal": Move("reversal", "fighting", "physical", None, 1.0, 15, None),
    "spite": Move("spite", "ghost", "status", None, 1.0, 10, None),
    "powder snow": Move("powder snow", "ice", "special", 40, 1.0, 25, None),
    "protect": Move("protect", "normal", "status", None, None, 10, None),
    "mach punch": Move("mach punch", "fighting", "physical", 40, 1.0, 30, None),
    "scary face": Move("scary face", "normal", "status", None, 1.0, 10, {"target_stat": ["opponent", "speed"], "change": [-2]}),
    "feint attack": Move("feint attack", "dark", "physical", 60, None, 20, None),
    "sweet kiss": Move("sweet kiss", "fairy", "status", None, 0.75, 10, None),
    "belly drum": Move("belly drum", "normal", "status", None, None, 10, None),
    "sludge bomb": Move("sludge bomb", "poison", "special", 90, 1.0, 10, None),
    "mud slap": Move("mud slap", "ground", "special", 20, 1.0, 10, {"target_stat": ["opponent", "accuracy"], "change": [-1]}),
    "octazooka": Move("octazooka", "water", "special", 65, 0.85, 10, {"target_stat": ["opponent", "accuracy"], "change": [-1]}),
    "spikes": Move("spikes", "ground", "status", None, None, 20, None),
    "zap cannon": Move("zap cannon", "electric", "special", 120, 0.5, 5, None),
    "foresight": Move("foresight", "normal", "status", None, None, 40, None),
    "destiny bond": Move("destiny bond", "ghost", "status", None, None, 5, None),
    "perish song": Move("perish song", "normal", "status", None, None, 5, None),
    "icy wind": Move("icy wind", "ice", "special", 55, 0.95, 15, {"target_stat": ["opponent", "speed"], "change": [-1]}),
    "detect": Move("detect", "fighting", "status", None, None, 5, None),
    "bone rush": Move("bone rush", "ground", "physical", 25, 0.9, 10, None),
    "lock on": Move("lock on", "normal", "status", None, None, 5, None),
    "outrage": Move("outrage", "dragon", "physical", 120, 1.0, 10, None),
    "sandstorm": Move("sandstorm", "rock", "status", None, None, 10, None),
    "giga drain": Move("giga drain", "grass", "special", 75, 1.0, 10, None),
    "endure": Move("endure", "normal", "status", None, None, 10, None),
    "charm": Move("charm", "fairy", "status", None, 1.0, 20, {"target_stat": ["opponent", "attack"], "change": [-2]}),
    "rollout": Move("rollout", "rock", "physical", 30, 0.9, 20, None),
    "false swipe": Move("false swipe", "normal", "physical", 40, 1.0, 40, None),
    "swagger": Move("swagger", "normal", "status", None, 0.85, 15, {"target_stat": ["opponent", "attack"], "change": [+2]}),
    "milk drink": Move("milk drink", "normal", "status", None, None, 5, None),
    "spark": Move("spark", "electric", "physical", 65, 1.0, 20, None),
    "fury cutter": Move("fury cutter", "bug", "physical", 40, 0.95, 20, None),
    "steel wing": Move("steel wing", "steel", "physical", 70, 0.9, 25, {"target_stat": ["opponent", "defense"], "change": [+1]}),
    "mean look": Move("mean look", "normal", "status", None, None, 5, None),
    "attract": Move("attract", "normal", "status", None, 1.0, 15, None),
    "sleep talk": Move("sleep talk", "normal", "status", None, None, 10, None),
    "heal bell": Move("heal bell", "normal", "status", None, None, 5, None),
    "return": Move("return", "normal", "physical", None, 1.0, 20, None),
    "present": Move("present", "normal", "physical", None, 0.9, 15, None),
    "frustration": Move("frustration", "normal", "physical", None, 1.0, 20, None),
    "safeguard": Move("safeguard", "normal", "status", None, None, 25, None),
    "pain split": Move("pain split", "normal", "status", None, None, 20, None),
    "sacred fire": Move("sacred fire", "fire", "physical", 100, 0.95, 5, None),
    "magnitude": Move("magnitude", "ground", "physical", None, 1.0, 30, None),
    "dynamic punch": Move("dynamic punch", "fighting", "physical", 100, 0.5, 5, None),
    "megahorn": Move("megahorn", "bug", "physical", 120, 0.85, 10, None),
    "dragon breath": Move("dragon breath", "dragon", "special", 60, 1.0, 20, None),
    "baton pass": Move("baton pass", "normal", "status", None, None, 40, None),
    "encore": Move("encore", "normal", "status", None, 1.0, 5, None),
    "pursuit": Move("pursuit", "dark", "physical", 40, 1.0, 20, None),
    "rapid spin": Move("rapid spin", "normal", "physical", 50, 1.0, 40, {"target_stat": ["opponent", "speed"], "change": [+1]}),
    "sweet scent": Move("sweet scent", "normal", "status", None, 1.0, 20, {"target_stat": ["opponent", "evasion"], "change": [-2]}),
    "iron tail": Move("iron tail", "steel", "physical", 100, 0.75, 15, {"target_stat": ["opponent", "defense"], "change": [-1]}),
    "metal claw": Move("metal claw", "steel", "physical", 50, 0.95, 35, {"target_stat": ["opponent", "attack"], "change": [+1]}),
    "vital throw": Move("vital throw", "fighting", "physical", 70, None, 10, None),
    "morning sun": Move("morning sun", "normal", "status", None, None, 5, None),
    "synthesis": Move("synthesis", "grass", "status", None, None, 5, None),
    "moonlight": Move("moonlight", "fairy", "status", None, None, 5, None),
    "hidden power": Move("hidden power", "normal", "special", 60, 1.0, 15, None),
    "cross chop": Move("cross chop", "fighting", "physical", 100, 0.8, 5, None),
    "twister": Move("twister", "dragon", "special", 40, 1.0, 20, None),
    "rain dance": Move("rain dance", "water", "status", None, None, 5, None),
    "sunny day": Move("sunny day", "fire", "status", None, None, 5, None),
    "crunch": Move("crunch", "dark", "physical", 80, 1.0, 15, {"target_stat": ["opponent", "defense"], "change": [-1]}),
    "mirror coat": Move("mirror coat", "psychic", "special", None, 1.0, 20, None),
    "psych up": Move("psych up", "normal", "status", None, None, 10, None),
    "extreme speed": Move("extreme speed", "normal", "physical", 80, 1.0, 5, None),
    "ancient power": Move("ancient power", "rock", "special", 60, 1.0, 5, {"target_stat": ["opponent", "attack", "defense", "special_attack", "special_defense", "speed"], "change": [+1, +1, +1, +1, +1]}),
    "shadow ball": Move("shadow ball", "ghost", "special", 80, 1.0, 15, {"target_stat": ["opponent", "special_defense"], "change": [-1]}),
    "future sight": Move("future sight", "psychic", "special", 120, 1.0, 10, None),
    "rock smash": Move("rock smash", "fighting", "physical", 40, 1.0, 15, {"target_stat": ["opponent", "defense"], "change": [-1]}),
    "whirlpool": Move("whirlpool", "water", "special", 35, 0.85, 15, None),
    "beat up": Move("beat up", "dark", "physical", None, 1.0, 10, None),
    "fake out": Move("fake out", "normal", "physical", 40, 1.0, 10, None),
    "uproar": Move("uproar", "normal", "special", 90, 1.0, 10, None),
    "stockpile": Move("stockpile", "normal", "status", None, None, 20, {"target_stat": ["self", "defense", "special_defense"], "change": [+1, +1]}),
    "spit up": Move("spit up", "normal", "special", None, 1.0, 10, None),
    "swallow": Move("swallow", "normal", "status", None, None, 10, None),
    "heat wave": Move("heat wave", "fire", "special", 95, 0.9, 10, None),
    "hail": Move("hail", "ice", "status", None, None, 10, None),
    "torment": Move("torment", "dark", "status", None, 1.0, 15, None),
    "flatter": Move("flatter", "dark", "status", None, 1.0, 15, {"target_stat": ["opponent", "special_attack"], "change": [+1]}),
    "will o wisp": Move("will o wisp", "fire", "status", None, 0.85, 15, None),
    "memento": Move("memento", "dark", "status", None, 1.0, 10, {"target_stat": ["opponent", "attack", "special_attack"], "change": [-2, -2]}),
    "facade": Move("facade", "normal", "physical", 70, 1.0, 20, None),
    "focus punch": Move("focus punch", "fighting", "physical", 150, 1.0, 20, None),
    "smelling salts": Move("smelling salts", "normal", "physical", 70, 1.0, 10, None),
    "follow me": Move("follow me", "normal", "status", None, None, 20, None),
    "nature power": Move("nature power", "normal", "status", None, None, 20, None),
    "charge": Move("charge", "electric", "status", None, None, 20, {"target_stat": ["self", "special_defense"], "change": [+1]}),
    "taunt": Move("taunt", "dark", "status", None, 1.0, 20, None),
    "helping hand": Move("helping hand", "normal", "status", None, None, 20, None),
    "trick": Move("trick", "psychic", "status", None, 1.0, 10, None),
    "role play": Move("role play", "psychic", "status", None, None, 10, None),
    "wish": Move("wish", "normal", "status", None, None, 10, None),
    "assist": Move("assist", "normal", "status", None, None, 20, None),
    "ingrain": Move("ingrain", "grass", "status", None, None, 20, None),
    "superpower": Move("superpower", "fighting", "physical", 120, 1.0, 5, {"target_stat": ["opponent", "attack", "defense"], "change": [-1, -1]}),
    "magic coat": Move("magic coat", "psychic", "status", None, None, 15, None),
    "recycle": Move("recycle", "normal", "status", None, None, 10, None),
    "revenge": Move("revenge", "fighting", "physical", 60, 1.0, 10, None),
    "brick break": Move("brick break", "fighting", "physical", 75, 1.0, 15, None),
    "yawn": Move("yawn", "normal", "status", None, None, 10, None),
    "knock off": Move("knock off", "dark", "physical", 65, 1.0, 20, None),
    "endeavor": Move("endeavor", "normal", "physical", None, 1.0, 5, None),
    "eruption": Move("eruption", "fire", "special", 150, 1.0, 5, None),
    "skill swap": Move("skill swap", "psychic", "status", None, None, 10, None),
    "imprison": Move("imprison", "psychic", "status", None, None, 10, None),
    "refresh": Move("refresh", "normal", "status", None, None, 20, None),
    "grudge": Move("grudge", "ghost", "status", None, None, 5, None),
    "snatch": Move("snatch", "dark", "status", None, None, 10, None),
    "secret power": Move("secret power", "normal", "physical", 70, 1.0, 20, None),
    "dive": Move("dive", "water", "physical", 80, 1.0, 10, None),
    "arm thrust": Move("arm thrust", "fighting", "physical", 15, 1.0, 20, None),
    "camouflage": Move("camouflage", "normal", "status", None, None, 20, None),
    "tail glow": Move("tail glow", "bug", "status", None, None, 20, {"target_stat": ["self", "special_attack"], "change": [+3]}),
    "luster purge": Move("luster purge", "psychic", "special", 95, 1.0, 5, {"target_stat": ["opponent", "special_defense"], "change": [-1]}),
    "mist ball": Move("mist ball", "psychic", "special", 95, 1.0, 5, {"target_stat": ["opponent", "special_attack"], "change": [-1]}),
    "feather dance": Move("feather dance", "flying", "status", None, 1.0, 15, {"target_stat": ["opponent", "attack"], "change": [-2]}),
    "teeter dance": Move("teeter dance", "normal", "status", None, 1.0, 20, None),
    "blaze kick": Move("blaze kick", "fire", "physical", 85, 0.9, 10, None),
    "mud sport": Move("mud sport", "ground", "status", None, None, 15, None),
    "ice ball": Move("ice ball", "ice", "physical", 30, 0.9, 20, None),
    "needle arm": Move("needle arm", "grass", "physical", 60, 1.0, 15, None),
    "slack off": Move("slack off", "normal", "status", None, None, 5, None),
    "hyper voice": Move("hyper voice", "normal", "special", 90, 1.0, 10, None),
    "poison fang": Move("poison fang", "poison", "physical", 50, 1.0, 15, None),
    "crush claw": Move("crush claw", "normal", "physical", 75, 0.95, 10, {"target_stat": ["opponent", "defense"], "change": [-1]}),
    "blast burn": Move("blast burn", "fire", "special", 150, 0.9, 5, None),
    "hydro cannon": Move("hydro cannon", "water", "special", 150, 0.9, 5, None),
    "meteor mash": Move("meteor mash", "steel", "physical", 90, 0.9, 10, {"target_stat": ["opponent", "attack"], "change": [+1]}),
    "astonish": Move("astonish", "ghost", "physical", 30, 1.0, 15, None),
    "weather ball": Move("weather ball", "normal", "special", 50, 1.0, 10, None),
    "aromatherapy": Move("aromatherapy", "grass", "status", None, None, 5, None),
    "fake tears": Move("fake tears", "dark", "status", None, 1.0, 20, {"target_stat": ["opponent", "special_defense"], "change": [-2]}),
    "air cutter": Move("air cutter", "flying", "special", 60, 0.95, 25, None),
    "overheat": Move("overheat", "fire", "special", 130, 0.9, 5, {"target_stat": ["opponent", "special_attack"], "change": [-2]}),
    "odor sleuth": Move("odor sleuth", "normal", "status", None, None, 40, None),
    "rock tomb": Move("rock tomb", "rock", "physical", 60, 0.95, 15, {"target_stat": ["opponent", "speed"], "change": [-1]}),
    "silver wind": Move("silver wind", "bug", "special", 60, 1.0, 5, {"target_stat": ["opponent", "attack", "defense", "special_attack", "special_defense", "speed"], "change": [+1, +1, +1, +1, +1]}),
    "metal sound": Move("metal sound", "steel", "status", None, 0.85, 40, {"target_stat": ["opponent", "special_defense"], "change": [-2]}),
    "grass whistle": Move("grass whistle", "grass", "status", None, 0.55, 15, None),
    "tickle": Move("tickle", "normal", "status", None, 1.0, 20, {"target_stat": ["opponent", "attack", "defense"], "change": [-1, -1]}),
    "cosmic power": Move("cosmic power", "psychic", "status", None, None, 20, {"target_stat": ["self", "defense", "special_defense"], "change": [+1, +1]}),
    "water spout": Move("water spout", "water", "special", 150, 1.0, 5, None),
    "signal beam": Move("signal beam", "bug", "special", 75, 1.0, 15, None),
    "shadow punch": Move("shadow punch", "ghost", "physical", 60, None, 20, None),
    "extrasensory": Move("extrasensory", "psychic", "special", 80, 1.0, 20, None),
    "sky uppercut": Move("sky uppercut", "fighting", "physical", 85, 0.9, 15, None),
    "sand tomb": Move("sand tomb", "ground", "physical", 35, 0.85, 15, None),
    "sheer cold": Move("sheer cold", "ice", "special", None, 0.3, 5, None),
    "muddy water": Move("muddy water", "water", "special", 90, 0.85, 10, {"target_stat": ["opponent", "accuracy"], "change": [-1]}),
    "bullet seed": Move("bullet seed", "grass", "physical", 25, 1.0, 30, None),
    "aerial ace": Move("aerial ace", "flying", "physical", 60, None, 20, None),
    "icicle spear": Move("icicle spear", "ice", "physical", 25, 1.0, 30, None),
    "iron defense": Move("iron defense", "steel", "status", None, None, 15, {"target_stat": ["self", "defense"], "change": [+2]}),
    "block": Move("block", "normal", "status", None, None, 5, None),
    "howl": Move("howl", "normal", "status", None, None, 40, {"target_stat": ["self", "attack"], "change": [+1]}),
    "dragon claw": Move("dragon claw", "dragon", "physical", 80, 1.0, 15, None),
    "frenzy plant": Move("frenzy plant", "grass", "special", 150, 0.9, 5, None),
    "bulk up": Move("bulk up", "fighting", "status", None, None, 20, {"target_stat": ["self", "attack", "defense"], "change": [+1, +1]}),
    "bounce": Move("bounce", "flying", "physical", 85, 0.85, 5, None),
    "mud shot": Move("mud shot", "ground", "special", 55, 0.95, 15, {"target_stat": ["opponent", "speed"], "change": [-1]}),
    "poison tail": Move("poison tail", "poison", "physical", 50, 1.0, 25, None),
    "covet": Move("covet", "normal", "physical", 60, 1.0, 25, None),
    "volt tackle": Move("volt tackle", "electric", "physical", 120, 1.0, 15, None),
    "magical leaf": Move("magical leaf", "grass", "special", 60, None, 20, None),
    "water sport": Move("water sport", "water", "status", None, None, 15, None),
    "calm mind": Move("calm mind", "psychic", "status", None, None, 20, {"target_stat": ["self", "special_attack", "special_defense"], "change": [+1, +1]}),
    "leaf blade": Move("leaf blade", "grass", "physical", 90, 1.0, 15, None),
    "dragon dance": Move("dragon dance", "dragon", "status", None, None, 20, {"target_stat": ["self", "attack", "speed"], "change": [+1, +1]}),
    "rock blast": Move("rock blast", "rock", "physical", 25, 0.9, 10, None),
    "shock wave": Move("shock wave", "electric", "special", 60, None, 20, None),
    "water pulse": Move("water pulse", "water", "special", 60, 1.0, 20, None),
    "doom desire": Move("doom desire", "steel", "special", 140, 1.0, 5, None),
    "psycho boost": Move("psycho boost", "psychic", "special", 140, 0.9, 5, {"target_stat": ["opponent", "special_attack"], "change": [-2]}),
    "roost": Move("roost", "flying", "status", None, None, 5, None),
    "gravity": Move("gravity", "psychic", "status", None, None, 5, None),
    "miracle eye": Move("miracle eye", "psychic", "status", None, None, 40, None),
    "wake up slap": Move("wake up slap", "fighting", "physical", 70, 1.0, 10, None),
    "hammer arm": Move("hammer arm", "fighting", "physical", 100, 0.9, 10, {"target_stat": ["opponent", "speed"], "change": [-1]}),
    "gyro ball": Move("gyro ball", "steel", "physical", None, 1.0, 5, None),
    "healing wish": Move("healing wish", "psychic", "status", None, None, 10, None),
    "brine": Move("brine", "water", "special", 65, 1.0, 10, None),
    "natural gift": Move("natural gift", "normal", "physical", None, 1.0, 15, None),
    "feint": Move("feint", "normal", "physical", 30, 1.0, 10, None),
    "pluck": Move("pluck", "flying", "physical", 60, 1.0, 20, None),
    "tailwind": Move("tailwind", "flying", "status", None, None, 15, None),
    "acupressure": Move("acupressure", "normal", "status", None, None, 30, None),
    "metal burst": Move("metal burst", "steel", "physical", None, 1.0, 10, None),
    "u turn": Move("u turn", "bug", "physical", 70, 1.0, 20, None),
    "close combat": Move("close combat", "fighting", "physical", 120, 1.0, 5, {"target_stat": ["opponent", "defense", "special_defense"], "change": [-1, -1]}),
    "payback": Move("payback", "dark", "physical", 50, 1.0, 10, None),
    "assurance": Move("assurance", "dark", "physical", 60, 1.0, 10, None),
    "embargo": Move("embargo", "dark", "status", None, 1.0, 15, None),
    "fling": Move("fling", "dark", "physical", None, 1.0, 10, None),
    "psycho shift": Move("psycho shift", "psychic", "status", None, 1.0, 10, None),
    "trump card": Move("trump card", "normal", "special", None, None, 5, None),
    "heal block": Move("heal block", "psychic", "status", None, 1.0, 15, None),
    "wring out": Move("wring out", "normal", "special", None, 1.0, 5, None),
    "power trick": Move("power trick", "psychic", "status", None, None, 10, None),
    "gastro acid": Move("gastro acid", "poison", "status", None, 1.0, 10, None),
    "lucky chant": Move("lucky chant", "normal", "status", None, None, 30, None),
    "me first": Move("me first", "normal", "status", None, None, 20, None),
    "copycat": Move("copycat", "normal", "status", None, None, 20, None),
    "power swap": Move("power swap", "psychic", "status", None, None, 10, None),
    "guard swap": Move("guard swap", "psychic", "status", None, None, 10, None),
    "punishment": Move("punishment", "dark", "physical", None, 1.0, 5, None),
    "last resort": Move("last resort", "normal", "physical", 140, 1.0, 5, None),
    "worry seed": Move("worry seed", "grass", "status", None, 1.0, 10, None),
    "sucker punch": Move("sucker punch", "dark", "physical", 70, 1.0, 5, None),
    "toxic spikes": Move("toxic spikes", "poison", "status", None, None, 20, None),
    "heart swap": Move("heart swap", "psychic", "status", None, None, 10, None),
    "aqua ring": Move("aqua ring", "water", "status", None, None, 20, None),
    "magnet rise": Move("magnet rise", "electric", "status", None, None, 10, None),
    "flare blitz": Move("flare blitz", "fire", "physical", 120, 1.0, 15, None),
    "force palm": Move("force palm", "fighting", "physical", 60, 1.0, 10, None),
    "aura sphere": Move("aura sphere", "fighting", "special", 80, None, 20, None),
    "rock polish": Move("rock polish", "rock", "status", None, None, 20, {"target_stat": ["self", "speed"], "change": [+2]}),
    "poison jab": Move("poison jab", "poison", "physical", 80, 1.0, 20, None),
    "dark pulse": Move("dark pulse", "dark", "special", 80, 1.0, 15, None),
    "night slash": Move("night slash", "dark", "physical", 70, 1.0, 15, None),
    "aqua tail": Move("aqua tail", "water", "physical", 90, 0.9, 10, None),
    "seed bomb": Move("seed bomb", "grass", "physical", 80, 1.0, 15, None),
    "air slash": Move("air slash", "flying", "special", 75, 0.95, 15, None),
    "x scissor": Move("x scissor", "bug", "physical", 80, 1.0, 15, None),
    "bug buzz": Move("bug buzz", "bug", "special", 90, 1.0, 10, {"target_stat": ["opponent", "special_defense"], "change": [-1]}),
    "dragon pulse": Move("dragon pulse", "dragon", "special", 85, 1.0, 10, None),
    "dragon rush": Move("dragon rush", "dragon", "physical", 100, 0.75, 10, None),
    "power gem": Move("power gem", "rock", "special", 80, 1.0, 20, None),
    "drain punch": Move("drain punch", "fighting", "physical", 75, 1.0, 10, None),
    "vacuum wave": Move("vacuum wave", "fighting", "special", 40, 1.0, 30, None),
    "focus blast": Move("focus blast", "fighting", "special", 120, 0.7, 5, {"target_stat": ["opponent", "special_defense"], "change": [-1]}),
    "energy ball": Move("energy ball", "grass", "special", 90, 1.0, 10, {"target_stat": ["opponent", "special_defense"], "change": [-1]}),
    "brave bird": Move("brave bird", "flying", "physical", 120, 1.0, 15, None),
    "earth power": Move("earth power", "ground", "special", 90, 1.0, 10, {"target_stat": ["opponent", "special_defense"], "change": [-1]}),
    "switcheroo": Move("switcheroo", "dark", "status", None, 1.0, 10, None),
    "giga impact": Move("giga impact", "normal", "physical", 150, 0.9, 5, None),
    "nasty plot": Move("nasty plot", "dark", "status", None, None, 20, {"target_stat": ["self", "special_attack"], "change": [+2]}),
    "bullet punch": Move("bullet punch", "steel", "physical", 40, 1.0, 30, None),
    "avalanche": Move("avalanche", "ice", "physical", 60, 1.0, 10, None),
    "ice shard": Move("ice shard", "ice", "physical", 40, 1.0, 30, None),
    "shadow claw": Move("shadow claw", "ghost", "physical", 70, 1.0, 15, None),
    "thunder fang": Move("thunder fang", "electric", "physical", 65, 0.95, 15, None),
    "ice fang": Move("ice fang", "ice", "physical", 65, 0.95, 15, None),
    "fire fang": Move("fire fang", "fire", "physical", 65, 0.95, 15, None),
    "shadow sneak": Move("shadow sneak", "ghost", "physical", 40, 1.0, 30, None),
    "mud bomb": Move("mud bomb", "ground", "special", 65, 0.85, 10, {"target_stat": ["opponent", "accuracy"], "change": [-1]}),
    "psycho cut": Move("psycho cut", "psychic", "physical", 70, 1.0, 20, None),
    "zen headbutt": Move("zen headbutt", "psychic", "physical", 80, 0.9, 15, None),
    "mirror shot": Move("mirror shot", "steel", "special", 65, 0.85, 10, {"target_stat": ["opponent", "accuracy"], "change": [-1]}),
    "flash cannon": Move("flash cannon", "steel", "special", 80, 1.0, 10, {"target_stat": ["opponent", "special_defense"], "change": [-1]}),
    "rock climb": Move("rock climb", "normal", "physical", 90, 0.85, 20, None),
    "defog": Move("defog", "flying", "status", None, None, 15, {"target_stat": ["opponent", "evasion"], "change": [-1]}),
    "trick room": Move("trick room", "psychic", "status", None, None, 5, None),
    "draco meteor": Move("draco meteor", "dragon", "special", 130, 0.9, 5, {"target_stat": ["opponent", "special_attack"], "change": [-2]}),
    "discharge": Move("discharge", "electric", "special", 80, 1.0, 15, None),
    "lava plume": Move("lava plume", "fire", "special", 80, 1.0, 15, None),
    "leaf storm": Move("leaf storm", "grass", "special", 130, 0.9, 5, {"target_stat": ["opponent", "special_attack"], "change": [-2]}),
    "power whip": Move("power whip", "grass", "physical", 120, 0.85, 10, None),
    "rock wrecker": Move("rock wrecker", "rock", "physical", 150, 0.9, 5, None),
    "cross poison": Move("cross poison", "poison", "physical", 70, 1.0, 20, None),
    "gunk shot": Move("gunk shot", "poison", "physical", 120, 0.8, 5, None),
    "iron head": Move("iron head", "steel", "physical", 80, 1.0, 15, None),
    "magnet bomb": Move("magnet bomb", "steel", "physical", 60, None, 20, None),
    "stone edge": Move("stone edge", "rock", "physical", 100, 0.8, 5, None),
    "captivate": Move("captivate", "normal", "status", None, 1.0, 20, {"target_stat": ["opponent", "special_attack"], "change": [-2]}),
    "stealth rock": Move("stealth rock", "rock", "status", None, None, 20, None),
    "grass knot": Move("grass knot", "grass", "special", None, 1.0, 20, None),
    "chatter": Move("chatter", "flying", "special", 65, 1.0, 20, None),
    "judgment": Move("judgment", "normal", "special", 100, 1.0, 10, None),
    "bug bite": Move("bug bite", "bug", "physical", 60, 1.0, 20, None),
    "charge beam": Move("charge beam", "electric", "special", 50, 0.9, 10, {"target_stat": ["opponent", "special_attack"], "change": [+1]}),
    "wood hammer": Move("wood hammer", "grass", "physical", 120, 1.0, 15, None),
    "aqua jet": Move("aqua jet", "water", "physical", 40, 1.0, 20, None),
    "attack order": Move("attack order", "bug", "physical", 90, 1.0, 15, None),
    "defend order": Move("defend order", "bug", "status", None, None, 10, {"target_stat": ["self", "defense", "special_defense"], "change": [+1, +1]}),
    "heal order": Move("heal order", "bug", "status", None, None, 10, None),
    "head smash": Move("head smash", "rock", "physical", 150, 0.8, 5, None),
    "double hit": Move("double hit", "normal", "physical", 35, 0.9, 10, None),
    "roar of time": Move("roar of time", "dragon", "special", 150, 0.9, 5, None),
    "spacial rend": Move("spacial rend", "dragon", "special", 100, 0.95, 5, None),
    "lunar dance": Move("lunar dance", "psychic", "status", None, None, 10, None),
    "crush grip": Move("crush grip", "normal", "physical", None, 1.0, 5, None),
    "magma storm": Move("magma storm", "fire", "special", 100, 0.75, 5, None),
    "dark void": Move("dark void", "dark", "status", None, 0.5, 10, None),
    "seed flare": Move("seed flare", "grass", "special", 120, 0.85, 5, {"target_stat": ["opponent", "special_defense"], "change": [-2]}),
    "ominous wind": Move("ominous wind", "ghost", "special", 60, 1.0, 5, {"target_stat": ["opponent", "attack", "defense", "special_attack", "special_defense", "speed"], "change": [+1, +1, +1, +1, +1]}),
    "shadow force": Move("shadow force", "ghost", "physical", 120, 1.0, 5, None),
    "hone claws": Move("hone claws", "dark", "status", None, None, 15, {"target_stat": ["self", "attack", "accuracy"], "change": [+1, +1]}),
    "wide guard": Move("wide guard", "rock", "status", None, None, 10, None),
    "guard split": Move("guard split", "psychic", "status", None, None, 10, None),
    "power split": Move("power split", "psychic", "status", None, None, 10, None),
    "wonder room": Move("wonder room", "psychic", "status", None, None, 10, None),
    "psyshock": Move("psyshock", "psychic", "special", 80, 1.0, 10, None),
    "venoshock": Move("venoshock", "poison", "special", 65, 1.0, 10, None),
    "autotomize": Move("autotomize", "steel", "status", None, None, 15, {"target_stat": ["self", "speed"], "change": [+2]}),
    "rage powder": Move("rage powder", "bug", "status", None, None, 20, None),
    "telekinesis": Move("telekinesis", "psychic", "status", None, None, 15, None),
    "magic room": Move("magic room", "psychic", "status", None, None, 10, None),
    "smack down": Move("smack down", "rock", "physical", 50, 1.0, 15, None),
    "storm throw": Move("storm throw", "fighting", "physical", 60, 1.0, 10, None),
    "flame burst": Move("flame burst", "fire", "special", 70, 1.0, 15, None),
    "sludge wave": Move("sludge wave", "poison", "special", 95, 1.0, 10, None),
    "quiver dance": Move("quiver dance", "bug", "status", None, None, 20, {"target_stat": ["self", "special_attack", "special_defense", "speed"], "change": [+1, +1, +1]}),
    "heavy slam": Move("heavy slam", "steel", "physical", None, 1.0, 10, None),
    "synchronoise": Move("synchronoise", "psychic", "special", 120, 1.0, 10, None),
    "electro ball": Move("electro ball", "electric", "special", None, 1.0, 10, None),
    "soak": Move("soak", "water", "status", None, 1.0, 20, None),
    "flame charge": Move("flame charge", "fire", "physical", 50, 1.0, 20, {"target_stat": ["opponent", "speed"], "change": [+1]}),
    "coil": Move("coil", "poison", "status", None, None, 20, {"target_stat": ["self", "attack", "defense", "accuracy"], "change": [+1, +1, +1]}),
    "low sweep": Move("low sweep", "fighting", "physical", 65, 1.0, 20, {"target_stat": ["opponent", "speed"], "change": [-1]}),
    "acid spray": Move("acid spray", "poison", "special", 40, 1.0, 20, {"target_stat": ["opponent", "special_defense"], "change": [-2]}),
    "foul play": Move("foul play", "dark", "physical", 95, 1.0, 15, None),
    "simple beam": Move("simple beam", "normal", "status", None, 1.0, 15, None),
    "entrainment": Move("entrainment", "normal", "status", None, 1.0, 15, None),
    "after you": Move("after you", "normal", "status", None, None, 15, None),
    "round": Move("round", "normal", "special", 60, 1.0, 15, None),
    "echoed voice": Move("echoed voice", "normal", "special", 40, 1.0, 15, None),
    "chip away": Move("chip away", "normal", "physical", 70, 1.0, 20, None),
    "clear smog": Move("clear smog", "poison", "special", 50, None, 15, None),
    "stored power": Move("stored power", "psychic", "special", 20, 1.0, 10, None),
    "quick guard": Move("quick guard", "fighting", "status", None, None, 15, None),
    "ally switch": Move("ally switch", "psychic", "status", None, None, 15, None),
    "scald": Move("scald", "water", "special", 80, 1.0, 15, None),
    "shell smash": Move("shell smash", "normal", "status", None, None, 15, {"target_stat": ["self", "defense", "special_defense", "attack", "special_attack", "speed"], "change": [-1, -1, +2, +2, +2]}),
    "heal pulse": Move("heal pulse", "psychic", "status", None, None, 10, None),
    "hex": Move("hex", "ghost", "special", 65, 1.0, 10, None),
    "sky drop": Move("sky drop", "flying", "physical", 60, 1.0, 10, None),
    "shift gear": Move("shift gear", "steel", "status", None, None, 10, {"target_stat": ["self", "attack", "speed"], "change": [+1, +2]}),
    "circle throw": Move("circle throw", "fighting", "physical", 60, 0.9, 10, None),
    "incinerate": Move("incinerate", "fire", "special", 60, 1.0, 15, None),
    "quash": Move("quash", "dark", "status", None, 1.0, 15, None),
    "acrobatics": Move("acrobatics", "flying", "physical", 55, 1.0, 15, None),
    "reflect type": Move("reflect type", "normal", "status", None, None, 15, None),
    "retaliate": Move("retaliate", "normal", "physical", 70, 1.0, 5, None),
    "final gambit": Move("final gambit", "fighting", "special", None, 1.0, 5, None),
    "bestow": Move("bestow", "normal", "status", None, None, 15, None),
    "inferno": Move("inferno", "fire", "special", 100, 0.5, 5, None),
    "water pledge": Move("water pledge", "water", "special", 80, 1.0, 10, None),
    "fire pledge": Move("fire pledge", "fire", "special", 80, 1.0, 10, None),
    "grass pledge": Move("grass pledge", "grass", "special", 80, 1.0, 10, None),
    "volt switch": Move("volt switch", "electric", "special", 70, 1.0, 20, None),
    "struggle bug": Move("struggle bug", "bug", "special", 50, 1.0, 20, {"target_stat": ["opponent", "special_attack"], "change": [-1]}),
    "bulldoze": Move("bulldoze", "ground", "physical", 60, 1.0, 20, {"target_stat": ["opponent", "speed"], "change": [-1]}),
    "frost breath": Move("frost breath", "ice", "special", 60, 0.9, 10, None),
    "dragon tail": Move("dragon tail", "dragon", "physical", 60, 0.9, 10, None),
    "work up": Move("work up", "normal", "status", None, None, 30, {"target_stat": ["self", "attack", "special_attack"], "change": [+1, +1]}),
    "electroweb": Move("electroweb", "electric", "special", 55, 0.95, 15, {"target_stat": ["opponent", "speed"], "change": [-1]}),
    "wild charge": Move("wild charge", "electric", "physical", 90, 1.0, 15, None),
    "drill run": Move("drill run", "ground", "physical", 80, 0.95, 10, None),
    "dual chop": Move("dual chop", "dragon", "physical", 40, 0.9, 15, None),
    "heart stamp": Move("heart stamp", "psychic", "physical", 60, 1.0, 25, None),
    "horn leech": Move("horn leech", "grass", "physical", 75, 1.0, 10, None),
    "sacred sword": Move("sacred sword", "fighting", "physical", 90, 1.0, 15, None),
    "razor shell": Move("razor shell", "water", "physical", 75, 0.95, 10, {"target_stat": ["opponent", "defense"], "change": [-1]}),
    "heat crash": Move("heat crash", "fire", "physical", None, 1.0, 10, None),
    "leaf tornado": Move("leaf tornado", "grass", "special", 65, 0.9, 10, {"target_stat": ["opponent", "accuracy"], "change": [-1]}),
    "steamroller": Move("steamroller", "bug", "physical", 65, 1.0, 20, None),
    "cotton guard": Move("cotton guard", "grass", "status", None, None, 10, {"target_stat": ["self", "defense"], "change": [+3]}),
    "night daze": Move("night daze", "dark", "special", 85, 0.95, 10, {"target_stat": ["opponent", "accuracy"], "change": [-1]}),
    "psystrike": Move("psystrike", "psychic", "special", 100, 1.0, 10, None),
    "tail slap": Move("tail slap", "normal", "physical", 25, 0.85, 10, None),
    "hurricane": Move("hurricane", "flying", "special", 110, 0.7, 10, None),
    "head charge": Move("head charge", "normal", "physical", 120, 1.0, 15, None),
    "gear grind": Move("gear grind", "steel", "physical", 50, 0.85, 15, None),
    "searing shot": Move("searing shot", "fire", "special", 100, 1.0, 5, None),
    "techno blast": Move("techno blast", "normal", "special", 120, 1.0, 5, None),
    "relic song": Move("relic song", "normal", "special", 75, 1.0, 10, None),
    "secret sword": Move("secret sword", "fighting", "special", 85, 1.0, 10, None),
    "glaciate": Move("glaciate", "ice", "special", 65, 0.95, 10, {"target_stat": ["opponent", "speed"], "change": [-1]}),
    "bolt strike": Move("bolt strike", "electric", "physical", 130, 0.85, 5, None),
    "blue flare": Move("blue flare", "fire", "special", 130, 0.85, 5, None),
    "fiery dance": Move("fiery dance", "fire", "special", 80, 1.0, 10, {"target_stat": ["opponent", "special_attack"], "change": [+1]}),
    "freeze shock": Move("freeze shock", "ice", "physical", 140, 0.9, 5, None),
    "ice burn": Move("ice burn", "ice", "special", 140, 0.9, 5, None),
    "snarl": Move("snarl", "dark", "special", 55, 0.95, 15, {"target_stat": ["opponent", "special_attack"], "change": [-1]}),
    "icicle crash": Move("icicle crash", "ice", "physical", 85, 0.9, 10, None),
    "v create": Move("v create", "fire", "physical", 180, 0.95, 5, {"target_stat": ["opponent", "defense", "special_defense", "speed"], "change": [-1, -1, -1]}),
    "fusion flare": Move("fusion flare", "fire", "special", 100, 1.0, 5, None),
    "fusion bolt": Move("fusion bolt", "electric", "physical", 100, 1.0, 5, None),
    "flying press": Move("flying press", "fighting", "physical", 100, 0.95, 10, None),
    "mat block": Move("mat block", "fighting", "status", None, None, 10, None),
    "belch": Move("belch", "poison", "special", 120, 0.9, 10, None),
    "rototiller": Move("rototiller", "ground", "status", None, None, 10, {"target_stat": ["opponent", "attack", "special_attack"], "change": [+1, +1]}),
    "sticky web": Move("sticky web", "bug", "status", None, None, 20, None),
    "fell stinger": Move("fell stinger", "bug", "physical", 50, 1.0, 25, None),
    "phantom force": Move("phantom force", "ghost", "physical", 90, 1.0, 10, None),
    "trick or treat": Move("trick or treat", "ghost", "status", None, 1.0, 20, None),
    "noble roar": Move("noble roar", "normal", "status", None, 1.0, 30, {"target_stat": ["opponent", "attack", "special_attack"], "change": [-1, -1]}),
    "ion deluge": Move("ion deluge", "electric", "status", None, None, 25, None),
    "parabolic charge": Move("parabolic charge", "electric", "special", 65, 1.0, 20, None),
    "forests curse": Move("forests curse", "grass", "status", None, 1.0, 20, None),
    "petal blizzard": Move("petal blizzard", "grass", "physical", 90, 1.0, 15, None),
    "freeze dry": Move("freeze dry", "ice", "special", 70, 1.0, 20, None),
    "disarming voice": Move("disarming voice", "fairy", "special", 40, None, 15, None),
    "parting shot": Move("parting shot", "dark", "status", None, 1.0, 20, {"target_stat": ["opponent", "attack", "special_attack"], "change": [-1, -1]}),
    "topsy turvy": Move("topsy turvy", "dark", "status", None, None, 20, None),
    "draining kiss": Move("draining kiss", "fairy", "special", 50, 1.0, 10, None),
    "crafty shield": Move("crafty shield", "fairy", "status", None, None, 10, None),
    "flower shield": Move("flower shield", "fairy", "status", None, None, 10, {"target_stat": ["opponent", "defense"], "change": [+1]}),
    "grassy terrain": Move("grassy terrain", "grass", "status", None, None, 10, None),
    "misty terrain": Move("misty terrain", "fairy", "status", None, None, 10, None),
    "electrify": Move("electrify", "electric", "status", None, None, 20, None),
    "play rough": Move("play rough", "fairy", "physical", 90, 0.9, 10, {"target_stat": ["opponent", "attack"], "change": [-1]}),
    "fairy wind": Move("fairy wind", "fairy", "special", 40, 1.0, 30, None),
    "moonblast": Move("moonblast", "fairy", "special", 95, 1.0, 15, {"target_stat": ["opponent", "special_attack"], "change": [-1]}),
    "boomburst": Move("boomburst", "normal", "special", 140, 1.0, 10, None),
    "fairy lock": Move("fairy lock", "fairy", "status", None, None, 10, None),
    "kings shield": Move("kings shield", "steel", "status", None, None, 10, None),
    "play nice": Move("play nice", "normal", "status", None, None, 20, {"target_stat": ["opponent", "attack"], "change": [-1]}),
    "confide": Move("confide", "normal", "status", None, None, 20, {"target_stat": ["opponent", "special_attack"], "change": [-1]}),
    "diamond storm": Move("diamond storm", "rock", "physical", 100, 0.95, 5, {"target_stat": ["opponent", "defense"], "change": [+2]}),
    "steam eruption": Move("steam eruption", "water", "special", 110, 0.95, 5, None),
    "hyperspace hole": Move("hyperspace hole", "psychic", "special", 80, None, 5, None),
    "water shuriken": Move("water shuriken", "water", "special", 15, 1.0, 20, None),
    "mystical fire": Move("mystical fire", "fire", "special", 75, 1.0, 10, {"target_stat": ["opponent", "special_attack"], "change": [-1]}),
    "spiky shield": Move("spiky shield", "grass", "status", None, None, 10, None),
    "aromatic mist": Move("aromatic mist", "fairy", "status", None, None, 20, {"target_stat": ["opponent", "special_defense"], "change": [+1]}),
    "eerie impulse": Move("eerie impulse", "electric", "status", None, 1.0, 15, {"target_stat": ["opponent", "special_attack"], "change": [-2]}),
    "venom drench": Move("venom drench", "poison", "status", None, 1.0, 20, {"target_stat": ["opponent", "attack", "special_attack", "speed"], "change": [-1, -1, -1]}),
    "powder": Move("powder", "bug", "status", None, 1.0, 20, None),
    "geomancy": Move("geomancy", "fairy", "status", None, None, 10, {"target_stat": ["self", "special_attack", "special_defense", "speed"], "change": [+2, +2, +2]}),
    "magnetic flux": Move("magnetic flux", "electric", "status", None, None, 20, {"target_stat": ["self", "defense", "special_defense"], "change": [+1, +1]}),
    "happy hour": Move("happy hour", "normal", "status", None, None, 30, None),
    "electric terrain": Move("electric terrain", "electric", "status", None, None, 10, None),
    "dazzling gleam": Move("dazzling gleam", "fairy", "special", 80, 1.0, 10, None),
    "celebrate": Move("celebrate", "normal", "status", None, None, 40, None),
    "hold hands": Move("hold hands", "normal", "status", None, None, 40, None),
    "baby doll eyes": Move("baby doll eyes", "fairy", "status", None, 1.0, 30, {"target_stat": ["opponent", "attack"], "change": [-1]}),
    "nuzzle": Move("nuzzle", "electric", "physical", 20, 1.0, 20, None),
    "hold back": Move("hold back", "normal", "physical", 40, 1.0, 40, None),
    "infestation": Move("infestation", "bug", "special", 20, 1.0, 20, None),
    "power up punch": Move("power up punch", "fighting", "physical", 40, 1.0, 20, {"target_stat": ["opponent", "attack"], "change": [+1]}),
    "oblivion wing": Move("oblivion wing", "flying", "special", 80, 1.0, 10, None),
    "thousand arrows": Move("thousand arrows", "ground", "physical", 90, 1.0, 10, None),
    "thousand waves": Move("thousand waves", "ground", "physical", 90, 1.0, 10, None),
    "lands wrath": Move("lands wrath", "ground", "physical", 90, 1.0, 10, None),
    "light of ruin": Move("light of ruin", "fairy", "special", 140, 0.9, 5, None),
    "origin pulse": Move("origin pulse", "water", "special", 110, 0.85, 10, None),
    "precipice blades": Move("precipice blades", "ground", "physical", 120, 0.85, 10, None),
    "dragon ascent": Move("dragon ascent", "flying", "physical", 120, 1.0, 5, {"target_stat": ["opponent", "defense", "special_defense"], "change": [-1, -1]}),
    "hyperspace fury": Move("hyperspace fury", "dark", "physical", 100, None, 5, {"target_stat": ["opponent", "defense"], "change": [-1]}),
    "breakneck blitz  physical": Move("breakneck blitz  physical", "normal", "physical", None, None, 1, None),
    "breakneck blitz  special": Move("breakneck blitz  special", "normal", "special", None, None, 1, None),
    "all out pummeling  physical": Move("all out pummeling  physical", "fighting", "physical", None, None, 1, None),
    "all out pummeling  special": Move("all out pummeling  special", "fighting", "special", None, None, 1, None),
    "supersonic skystrike  physical": Move("supersonic skystrike  physical", "flying", "physical", None, None, 1, None),
    "supersonic skystrike  special": Move("supersonic skystrike  special", "flying", "special", None, None, 1, None),
    "acid downpour  physical": Move("acid downpour  physical", "poison", "physical", None, None, 1, None),
    "acid downpour  special": Move("acid downpour  special", "poison", "special", None, None, 1, None),
    "tectonic rage  physical": Move("tectonic rage  physical", "ground", "physical", None, None, 1, None),
    "tectonic rage  special": Move("tectonic rage  special", "ground", "special", None, None, 1, None),
    "continental crush  physical": Move("continental crush  physical", "rock", "physical", None, None, 1, None),
    "continental crush  special": Move("continental crush  special", "rock", "special", None, None, 1, None),
    "savage spin out  physical": Move("savage spin out  physical", "bug", "physical", None, None, 1, None),
    "savage spin out  special": Move("savage spin out  special", "bug", "special", None, None, 1, None),
    "never ending nightmare  physical": Move("never ending nightmare  physical", "ghost", "physical", None, None, 1, None),
    "never ending nightmare  special": Move("never ending nightmare  special", "ghost", "special", None, None, 1, None),
    "corkscrew crash  physical": Move("corkscrew crash  physical", "steel", "physical", None, None, 1, None),
    "corkscrew crash  special": Move("corkscrew crash  special", "steel", "special", None, None, 1, None),
    "inferno overdrive  physical": Move("inferno overdrive  physical", "fire", "physical", None, None, 1, None),
    "inferno overdrive  special": Move("inferno overdrive  special", "fire", "special", None, None, 1, None),
    "hydro vortex  physical": Move("hydro vortex  physical", "water", "physical", None, None, 1, None),
    "hydro vortex  special": Move("hydro vortex  special", "water", "special", None, None, 1, None),
    "bloom doom  physical": Move("bloom doom  physical", "grass", "physical", None, None, 1, None),
    "bloom doom  special": Move("bloom doom  special", "grass", "special", None, None, 1, None),
    "gigavolt havoc  physical": Move("gigavolt havoc  physical", "electric", "physical", None, None, 1, None),
    "gigavolt havoc  special": Move("gigavolt havoc  special", "electric", "special", None, None, 1, None),
    "shattered psyche  physical": Move("shattered psyche  physical", "psychic", "physical", None, None, 1, None),
    "shattered psyche  special": Move("shattered psyche  special", "psychic", "special", None, None, 1, None),
    "subzero slammer  physical": Move("subzero slammer  physical", "ice", "physical", None, None, 1, None),
    "subzero slammer  special": Move("subzero slammer  special", "ice", "special", None, None, 1, None),
    "devastating drake  physical": Move("devastating drake  physical", "dragon", "physical", None, None, 1, None),
    "devastating drake  special": Move("devastating drake  special", "dragon", "special", None, None, 1, None),
    "black hole eclipse  physical": Move("black hole eclipse  physical", "dark", "physical", None, None, 1, None),
    "black hole eclipse  special": Move("black hole eclipse  special", "dark", "special", None, None, 1, None),
    "twinkle tackle  physical": Move("twinkle tackle  physical", "fairy", "physical", None, None, 1, None),
    "twinkle tackle  special": Move("twinkle tackle  special", "fairy", "special", None, None, 1, None),
    "catastropika": Move("catastropika", "electric", "physical", 210, None, 1, None),
    "shore up": Move("shore up", "ground", "status", None, None, 5, None),
    "first impression": Move("first impression", "bug", "physical", 90, 1.0, 10, None),
    "baneful bunker": Move("baneful bunker", "poison", "status", None, None, 10, None),
    "spirit shackle": Move("spirit shackle", "ghost", "physical", 80, 1.0, 10, None),
    "darkest lariat": Move("darkest lariat", "dark", "physical", 85, 1.0, 10, None),
    "sparkling aria": Move("sparkling aria", "water", "special", 90, 1.0, 10, None),
    "ice hammer": Move("ice hammer", "ice", "physical", 100, 0.9, 10, {"target_stat": ["opponent", "speed"], "change": [-1]}),
    "floral healing": Move("floral healing", "fairy", "status", None, None, 10, None),
    "high horsepower": Move("high horsepower", "ground", "physical", 95, 0.95, 10, None),
    "strength sap": Move("strength sap", "grass", "status", None, 1.0, 10, {"target_stat": ["opponent", "attack"], "change": [-1]}),
    "solar blade": Move("solar blade", "grass", "physical", 125, 1.0, 10, None),
    "leafage": Move("leafage", "grass", "physical", 40, 1.0, 40, None),
    "spotlight": Move("spotlight", "normal", "status", None, None, 15, None),
    "toxic thread": Move("toxic thread", "poison", "status", None, 1.0, 20, {"target_stat": ["opponent", "speed"], "change": [-1]}),
    "laser focus": Move("laser focus", "normal", "status", None, None, 30, None),
    "gear up": Move("gear up", "steel", "status", None, None, 20, {"target_stat": ["self", "attack", "special_attack"], "change": [+1, +1]}),
    "throat chop": Move("throat chop", "dark", "physical", 80, 1.0, 15, None),
    "pollen puff": Move("pollen puff", "bug", "special", 90, 1.0, 15, None),
    "anchor shot": Move("anchor shot", "steel", "physical", 80, 1.0, 20, None),
    "psychic terrain": Move("psychic terrain", "psychic", "status", None, None, 10, None),
    "lunge": Move("lunge", "bug", "physical", 80, 1.0, 15, {"target_stat": ["opponent", "attack"], "change": [-1]}),
    "fire lash": Move("fire lash", "fire", "physical", 80, 1.0, 15, {"target_stat": ["opponent", "defense"], "change": [-1]}),
    "power trip": Move("power trip", "dark", "physical", 20, 1.0, 10, None),
    "burn up": Move("burn up", "fire", "special", 130, 1.0, 5, None),
    "speed swap": Move("speed swap", "psychic", "status", None, None, 10, None),
    "smart strike": Move("smart strike", "steel", "physical", 70, None, 10, None),
    "purify": Move("purify", "poison", "status", None, None, 20, None),
    "revelation dance": Move("revelation dance", "normal", "special", 90, 1.0, 15, None),
    "core enforcer": Move("core enforcer", "dragon", "special", 100, 1.0, 10, None),
    "trop kick": Move("trop kick", "grass", "physical", 70, 1.0, 15, {"target_stat": ["opponent", "attack"], "change": [-1]}),
    "instruct": Move("instruct", "psychic", "status", None, None, 15, None),
    "beak blast": Move("beak blast", "flying", "physical", 100, 1.0, 15, None),
    "clanging scales": Move("clanging scales", "dragon", "special", 110, 1.0, 5, {"target_stat": ["opponent", "defense"], "change": [-1]}),
    "dragon hammer": Move("dragon hammer", "dragon", "physical", 90, 1.0, 15, None),
    "brutal swing": Move("brutal swing", "dark", "physical", 60, 1.0, 20, None),
    "aurora veil": Move("aurora veil", "ice", "status", None, None, 20, None),
    "sinister arrow raid": Move("sinister arrow raid", "ghost", "physical", 180, None, 1, None),
    "malicious moonsault": Move("malicious moonsault", "dark", "physical", 180, None, 1, None),
    "oceanic operetta": Move("oceanic operetta", "water", "special", 195, None, 1, None),
    "guardian of alola": Move("guardian of alola", "fairy", "special", None, None, 1, None),
    "soul stealing 7 star strike": Move("soul stealing 7 star strike", "ghost", "physical", 195, None, 1, None),
    "stoked sparksurfer": Move("stoked sparksurfer", "electric", "special", 175, None, 1, None),
    "pulverizing pancake": Move("pulverizing pancake", "normal", "physical", 210, None, 1, None),
    "extreme evoboost": Move("extreme evoboost", "normal", "status", None, None, 1, {"target_stat": ["self", "attack", "defense", "special_attack", "special_defense", "speed"], "change": [+2, +2, +2, +2, +2]}),
    "genesis supernova": Move("genesis supernova", "psychic", "special", 185, None, 1, None),
    "shell trap": Move("shell trap", "fire", "special", 150, 1.0, 5, None),
    "fleur cannon": Move("fleur cannon", "fairy", "special", 130, 0.9, 5, {"target_stat": ["opponent", "special_attack"], "change": [-2]}),
    "psychic fangs": Move("psychic fangs", "psychic", "physical", 85, 1.0, 10, None),
    "stomping tantrum": Move("stomping tantrum", "ground", "physical", 75, 1.0, 10, None),
    "shadow bone": Move("shadow bone", "ghost", "physical", 85, 1.0, 10, {"target_stat": ["opponent", "defense"], "change": [-1]}),
    "accelerock": Move("accelerock", "rock", "physical", 40, 1.0, 20, None),
    "liquidation": Move("liquidation", "water", "physical", 85, 1.0, 10, {"target_stat": ["opponent", "defense"], "change": [-1]}),
    "prismatic laser": Move("prismatic laser", "psychic", "special", 160, 1.0, 10, None),
    "spectral thief": Move("spectral thief", "ghost", "physical", 90, 1.0, 10, None),
    "sunsteel strike": Move("sunsteel strike", "steel", "physical", 100, 1.0, 5, None),
    "moongeist beam": Move("moongeist beam", "ghost", "special", 100, 1.0, 5, None),
    "tearful look": Move("tearful look", "normal", "status", None, None, 20, {"target_stat": ["opponent", "attack", "special_attack"], "change": [-1, -1]}),
    "zing zap": Move("zing zap", "electric", "physical", 80, 1.0, 10, None),
    "natures madness": Move("natures madness", "fairy", "special", None, 0.9, 10, None),
    "multi attack": Move("multi attack", "normal", "physical", 120, 1.0, 10, None),
    "10 000 000 volt thunderbolt": Move("10 000 000 volt thunderbolt", "electric", "special", 195, None, 1, None),
    "mind blown": Move("mind blown", "fire", "special", 150, 1.0, 5, None),
    "plasma fists": Move("plasma fists", "electric", "physical", 100, 1.0, 15, None),
    "photon geyser": Move("photon geyser", "psychic", "special", 100, 1.0, 5, None),
    "light that burns the sky": Move("light that burns the sky", "psychic", "special", 200, None, 1, None),
    "searing sunraze smash": Move("searing sunraze smash", "steel", "physical", 200, None, 1, None),
    "menacing moonraze maelstrom": Move("menacing moonraze maelstrom", "ghost", "special", 200, None, 1, None),
    "lets snuggle forever": Move("lets snuggle forever", "fairy", "physical", 190, None, 1, None),
    "splintered stormshards": Move("splintered stormshards", "rock", "physical", 190, None, 1, None),
    "clangorous soulblaze": Move("clangorous soulblaze", "dragon", "special", 185, None, 1, {"target_stat": ["opponent", "attack", "defense", "special_attack", "special_defense", "speed"], "change": [+1, +1, +1, +1, +1]}),
    "zippy zap": Move("zippy zap", "electric", "physical", 80, 1.0, 10, {"target_stat": ["opponent", "evasion"], "change": [+1]}),
    "splishy splash": Move("splishy splash", "water", "special", 90, 1.0, 15, None),
    "floaty fall": Move("floaty fall", "flying", "physical", 90, 0.95, 15, None),
    "pika papow": Move("pika papow", "electric", "special", None, None, 20, None),
    "bouncy bubble": Move("bouncy bubble", "water", "special", 60, 1.0, 20, None),
    "buzzy buzz": Move("buzzy buzz", "electric", "special", 60, 1.0, 20, None),
    "sizzly slide": Move("sizzly slide", "fire", "physical", 60, 1.0, 20, None),
    "glitzy glow": Move("glitzy glow", "psychic", "special", 80, 0.95, 15, None),
    "baddy bad": Move("baddy bad", "dark", "special", 80, 0.95, 15, None),
    "sappy seed": Move("sappy seed", "grass", "physical", 100, 0.9, 10, None),
    "freezy frost": Move("freezy frost", "ice", "special", 100, 0.9, 10, None),
    "sparkly swirl": Move("sparkly swirl", "fairy", "special", 120, 0.85, 5, None),
    "veevee volley": Move("veevee volley", "normal", "physical", None, None, 20, None),
    "double iron bash": Move("double iron bash", "steel", "physical", 60, 1.0, 5, None),
    "max guard": Move("max guard", "normal", "status", None, None, 10, None),
    "dynamax cannon": Move("dynamax cannon", "dragon", "special", 100, 1.0, 5, None),
    "snipe shot": Move("snipe shot", "water", "special", 80, 1.0, 15, None),
    "jaw lock": Move("jaw lock", "dark", "physical", 80, 1.0, 10, None),
    "stuff cheeks": Move("stuff cheeks", "normal", "status", None, None, 10, {"target_stat": ["self", "defense"], "change": [+2]}),
    "no retreat": Move("no retreat", "fighting", "status", None, None, 5, {"target_stat": ["self", "attack", "defense", "special_attack", "special_defense", "speed"], "change": [+1, +1, +1, +1, +1]}),
    "tar shot": Move("tar shot", "rock", "status", None, 1.0, 15, {"target_stat": ["opponent", "speed"], "change": [-1]}),
    "magic powder": Move("magic powder", "psychic", "status", None, 1.0, 20, None),
    "dragon darts": Move("dragon darts", "dragon", "physical", 50, 1.0, 10, None),
    "teatime": Move("teatime", "normal", "status", None, None, 10, None),
    "octolock": Move("octolock", "fighting", "status", None, 1.0, 15, None),
    "bolt beak": Move("bolt beak", "electric", "physical", 85, 1.0, 10, None),
    "fishious rend": Move("fishious rend", "water", "physical", 85, 1.0, 10, None),
    "court change": Move("court change", "normal", "status", None, 1.0, 10, None),
    "max flare": Move("max flare", "fire", "physical", 100, None, 10, None),
    "max flutterby": Move("max flutterby", "bug", "physical", 10, None, 10, None),
    "max lightning": Move("max lightning", "electric", "physical", 10, None, 10, None),
    "max strike": Move("max strike", "normal", "physical", 10, None, 10, None),
    "max knuckle": Move("max knuckle", "fighting", "physical", 10, None, 10, None),
    "max phantasm": Move("max phantasm", "ghost", "physical", 10, None, 10, None),
    "max hailstorm": Move("max hailstorm", "ice", "physical", 10, None, 10, None),
    "max ooze": Move("max ooze", "poison", "physical", 10, None, 10, None),
    "max geyser": Move("max geyser", "water", "physical", 10, None, 10, None),
    "max airstream": Move("max airstream", "flying", "physical", 10, None, 10, None),
    "max starfall": Move("max starfall", "fairy", "physical", 10, None, 10, None),
    "max wyrmwind": Move("max wyrmwind", "dragon", "physical", 10, None, 10, None),
    "max mindstorm": Move("max mindstorm", "psychic", "physical", 10, None, 10, None),
    "max rockfall": Move("max rockfall", "rock", "physical", 10, None, 10, None),
    "max quake": Move("max quake", "ground", "physical", 10, None, 10, None),
    "max darkness": Move("max darkness", "dark", "physical", 10, None, 10, None),
    "max overgrowth": Move("max overgrowth", "grass", "physical", 10, None, 10, None),
    "max steelspike": Move("max steelspike", "steel", "physical", 10, None, 10, None),
    "clangorous soul": Move("clangorous soul", "dragon", "status", None, 1.0, 5, {"target_stat": ["self", "attack", "defense", "special_attack", "special_defense", "speed"], "change": [+1, +1, +1, +1, +1]}),
    "body press": Move("body press", "fighting", "physical", 80, 1.0, 10, None),
    "decorate": Move("decorate", "fairy", "status", None, None, 15, {"target_stat": ["opponent", "attack", "special_attack"], "change": [+2, +2]}),
    "drum beating": Move("drum beating", "grass", "physical", 80, 1.0, 10, {"target_stat": ["opponent", "speed"], "change": [-1]}),
    "snap trap": Move("snap trap", "grass", "physical", 35, 1.0, 15, None),
    "pyro ball": Move("pyro ball", "fire", "physical", 120, 0.9, 5, None),
    "behemoth blade": Move("behemoth blade", "steel", "physical", 100, 1.0, 5, None),
    "behemoth bash": Move("behemoth bash", "steel", "physical", 100, 1.0, 5, None),
    "aura wheel": Move("aura wheel", "electric", "physical", 110, 1.0, 10, {"target_stat": ["opponent", "speed"], "change": [+1]}),
    "breaking swipe": Move("breaking swipe", "dragon", "physical", 60, 1.0, 15, {"target_stat": ["opponent", "attack"], "change": [-1]}),
    "branch poke": Move("branch poke", "grass", "physical", 40, 1.0, 40, None),
    "overdrive": Move("overdrive", "electric", "special", 80, 1.0, 10, None),
    "apple acid": Move("apple acid", "grass", "special", 80, 1.0, 10, {"target_stat": ["opponent", "special_defense"], "change": [-1]}),
    "grav apple": Move("grav apple", "grass", "physical", 80, 1.0, 10, {"target_stat": ["opponent", "defense"], "change": [-1]}),
    "spirit break": Move("spirit break", "fairy", "physical", 75, 1.0, 15, {"target_stat": ["opponent", "special_attack"], "change": [-1]}),
    "strange steam": Move("strange steam", "fairy", "special", 90, 0.95, 10, None),
    "life dew": Move("life dew", "water", "status", None, None, 10, None),
    "obstruct": Move("obstruct", "dark", "status", None, 1.0, 10, None),
    "false surrender": Move("false surrender", "dark", "physical", 80, None, 10, None),
    "meteor assault": Move("meteor assault", "fighting", "physical", 150, 1.0, 5, None),
    "eternabeam": Move("eternabeam", "dragon", "special", 160, 0.9, 5, None),
    "steel beam": Move("steel beam", "steel", "special", 140, 0.95, 5, None),
    "expanding force": Move("expanding force", "psychic", "special", 80, 1.0, 10, None),
    "steel roller": Move("steel roller", "steel", "physical", 130, 1.0, 5, None),
    "scale shot": Move("scale shot", "dragon", "physical", 25, 0.9, 20, None),
    "meteor beam": Move("meteor beam", "rock", "special", 120, 0.9, 10, None),
    "shell side arm": Move("shell side arm", "poison", "special", 90, 1.0, 10, None),
    "misty explosion": Move("misty explosion", "fairy", "special", 100, 1.0, 5, None),
    "grassy glide": Move("grassy glide", "grass", "physical", 55, 1.0, 20, None),
    "rising voltage": Move("rising voltage", "electric", "special", 70, 1.0, 20, None),
    "terrain pulse": Move("terrain pulse", "normal", "special", 50, 1.0, 10, None),
    "skitter smack": Move("skitter smack", "bug", "physical", 70, 0.9, 10, {"target_stat": ["opponent", "special_attack"], "change": [-1]}),
    "burning jealousy": Move("burning jealousy", "fire", "special", 70, 1.0, 5, None),
    "lash out": Move("lash out", "dark", "physical", 75, 1.0, 5, None),
    "poltergeist": Move("poltergeist", "ghost", "physical", 110, 0.9, 5, None),
    "corrosive gas": Move("corrosive gas", "poison", "status", None, 1.0, 40, None),
    "coaching": Move("coaching", "fighting", "status", None, None, 10, {"target_stat": ["self", "attack", "defense"], "change": [+1, +1]}),
    "flip turn": Move("flip turn", "water", "physical", 60, 1.0, 20, None),
    "triple axel": Move("triple axel", "ice", "physical", 20, 0.9, 10, None),
    "dual wingbeat": Move("dual wingbeat", "flying", "physical", 40, 0.9, 10, None),
    "scorching sands": Move("scorching sands", "ground", "special", 70, 1.0, 10, None),
    "jungle healing": Move("jungle healing", "grass", "status", None, None, 10, None),
    "wicked blow": Move("wicked blow", "dark", "physical", 75, 1.0, 5, None),
    "surging strikes": Move("surging strikes", "water", "physical", 25, 1.0, 5, None),
    "thunder cage": Move("thunder cage", "electric", "special", 80, 0.9, 15, None),
    "dragon energy": Move("dragon energy", "dragon", "special", 150, 1.0, 5, None),
    "freezing glare": Move("freezing glare", "psychic", "special", 90, 1.0, 10, None),
    "fiery wrath": Move("fiery wrath", "dark", "special", 90, 1.0, 10, None),
    "thunderous kick": Move("thunderous kick", "fighting", "physical", 90, 1.0, 10, {"target_stat": ["opponent", "defense"], "change": [-1]}),
    "glacial lance": Move("glacial lance", "ice", "physical", 120, 1.0, 5, None),
    "astral barrage": Move("astral barrage", "ghost", "special", 120, 1.0, 5, None),
    "eerie spell": Move("eerie spell", "psychic", "special", 80, 1.0, 5, None),
    "dire claw": Move("dire claw", "poison", "physical", 80, 1.0, 15, None),
    "psyshield bash": Move("psyshield bash", "psychic", "physical", 70, 0.9, 10, None),
    "power shift": Move("power shift", "normal", "status", 0, None, 10, None),
    "stone axe": Move("stone axe", "rock", "physical", 65, 0.9, 15, None),
    "springtide storm": Move("springtide storm", "fairy", "special", 100, 0.8, 5, None),
    "mystical power": Move("mystical power", "psychic", "special", 70, 0.9, 10, None),
    "raging fury": Move("raging fury", "fire", "physical", 120, 1.0, 10, None),
    "wave crash": Move("wave crash", "water", "physical", 120, 1.0, 10, None),
    "chloroblast": Move("chloroblast", "grass", "special", 150, 0.95, 5, None),
    "mountain gale": Move("mountain gale", "ice", "physical", 100, 0.85, 10, None),
    "victory dance": Move("victory dance", "fighting", "status", 0, None, 10, None),
    "headlong rush": Move("headlong rush", "ground", "physical", 120, 1.0, 5, None),
    "barb barrage": Move("barb barrage", "poison", "physical", 60, 1.0, 10, None),
    "esper wing": Move("esper wing", "psychic", "special", 80, 1.0, 10, None),
    "bitter malice": Move("bitter malice", "ghost", "special", 75, 1.0, 10, None),
    "shelter": Move("shelter", "steel", "status", 0, None, 10, None),
    "triple arrows": Move("triple arrows", "fighting", "physical", 90, 1.0, 10, None),
    "infernal parade": Move("infernal parade", "ghost", "special", 60, 1.0, 15, None),
    "ceaseless edge": Move("ceaseless edge", "dark", "physical", 65, 0.9, 15, None),
    "bleakwind storm": Move("bleakwind storm", "flying", "special", 100, 0.8, 10, None),
    "wildbolt storm": Move("wildbolt storm", "electric", "special", 100, 0.8, 10, None),
    "sandsear storm": Move("sandsear storm", "ground", "special", 100, 0.8, 10, None),
    "lunar blessing": Move("lunar blessing", "psychic", "status", 0, None, 5, None),
    "take heart": Move("take heart", "psychic", "status", 0, None, 10, None),
    "tera blast": Move("tera blast", "normal", "special", 80, 1.0, 10, {"target_stat": ["opponent", "attack", "special_attack"], "change": [-1, -1]}),
    "silk trap": Move("silk trap", "bug", "status", 0, None, 10, {"target_stat": ["self", "speed"], "change": [-1]}),
    "axe kick": Move("axe kick", "fighting", "physical", 120, 0.9, 10, None),
    "last respects": Move("last respects", "ghost", "physical", 50, 1.0, 10, None),
    "lumina crash": Move("lumina crash", "psychic", "special", 80, 1.0, 10, {"target_stat": ["opponent", "special_defense"], "change": [-2]}),
    "order up": Move("order up", "dragon", "physical", 80, 1.0, 10, None),
    "jet punch": Move("jet punch", "water", "physical", 60, 1.0, 15, None),
    "spicy extract": Move("spicy extract", "grass", "status", 0, None, 15, {"target_stat": ["opponent", "attack", "defense"], "change": [+2, -2]}),
    "spin out": Move("spin out", "steel", "physical", 100, 1.0, 5, {"target_stat": ["opponent", "speed"], "change": [-2]}),
    "population bomb": Move("population bomb", "normal", "physical", 20, 0.9, 10, None),
    "ice spinner": Move("ice spinner", "ice", "physical", 80, 1.0, 15, None),
    "glaive rush": Move("glaive rush", "dragon", "physical", 120, 1.0, 5, None),
    "revival blessing": Move("revival blessing", "normal", "status", 0, None, 1, None),
    "salt cure": Move("salt cure", "rock", "physical", 40, 1.0, 15, None),
    "triple dive": Move("triple dive", "water", "physical", 30, 0.95, 10, None),
    "mortal spin": Move("mortal spin", "poison", "physical", 30, 1.0, 15, None),
    "doodle": Move("doodle", "normal", "status", 0, 1.0, 10, None),
    "fillet away": Move("fillet away", "normal", "status", 0, None, 10, {"target_stat": ["self", "attack", "special_attack", "speed"], "change": [+2, +2, +2]}),
    "kowtow cleave": Move("kowtow cleave", "dark", "physical", 85, None, 10, None),
    "flower trick": Move("flower trick", "grass", "physical", 70, None, 10, None),
    "torch song": Move("torch song", "fire", "special", 80, 1.0, 10, {"target_stat": ["opponent", "special_attack"], "change": [+1]}),
    "aqua step": Move("aqua step", "water", "physical", 80, 1.0, 10, {"target_stat": ["opponent", "speed"], "change": [+1]}),
    "raging bull": Move("raging bull", "normal", "physical", 90, 1.0, 10, None),
    "make it rain": Move("make it rain", "steel", "special", 120, 1.0, 5, {"target_stat": ["opponent", "special_attack"], "change": [-1]}),
    "psyblade": Move("psyblade", "psychic", "physical", 80, 1.0, 15, None),
    "hydro steam": Move("hydro steam", "water", "special", 80, 1.0, 15, None),
    "ruination": Move("ruination", "dark", "special", 1, 0.9, 10, None),
    "collision course": Move("collision course", "fighting", "physical", 100, 1.0, 5, None),
    "electro drift": Move("electro drift", "electric", "special", 100, 1.0, 5, None),
    "shed tail": Move("shed tail", "normal", "status", 0, None, 10, None),
    "chilly reception": Move("chilly reception", "ice", "status", 0, None, 10, None),
    "tidy up": Move("tidy up", "normal", "status", 0, None, 10, {"target_stat": ["self", "attack", "speed"], "change": [+1, +1]}),
    "snowscape": Move("snowscape", "ice", "status", 0, None, 10, None),
    "pounce": Move("pounce", "bug", "physical", 50, 1.0, 20, {"target_stat": ["opponent", "speed"], "change": [-1]}),
    "trailblaze": Move("trailblaze", "grass", "physical", 50, 1.0, 20, {"target_stat": ["opponent", "speed"], "change": [+1]}),
    "chilling water": Move("chilling water", "water", "special", 50, 1.0, 20, {"target_stat": ["opponent", "attack"], "change": [-1]}),
    "hyper drill": Move("hyper drill", "normal", "physical", 100, 1.0, 5, None),
    "twin beam": Move("twin beam", "psychic", "special", 40, 1.0, 10, None),
    "rage fist": Move("rage fist", "ghost", "physical", 50, 1.0, 10, None),
    "armor cannon": Move("armor cannon", "fire", "special", 120, 1.0, 5, {"target_stat": ["opponent", "defense", "special_defense"], "change": [-1, -1]}),
    "bitter blade": Move("bitter blade", "fire", "physical", 90, 1.0, 10, None),
    "double shock": Move("double shock", "electric", "physical", 120, 1.0, 5, None),
    "gigaton hammer": Move("gigaton hammer", "steel", "physical", 160, 1.0, 5, None),
    "comeuppance": Move("comeuppance", "dark", "physical", 1, 1.0, 10, None),
    "aqua cutter": Move("aqua cutter", "water", "physical", 70, 1.0, 20, None),
    "blazing torque": Move("blazing torque", "fire", "physical", 80, 1.0, 10, None),
    "wicked torque": Move("wicked torque", "dark", "physical", 80, 1.0, 10, None),
    "noxious torque": Move("noxious torque", "poison", "physical", 100, 1.0, 10, None),
    "combat torque": Move("combat torque", "fighting", "physical", 100, 1.0, 10, None),
    "magical torque": Move("magical torque", "fairy", "physical", 100, 1.0, 10, None),
    "blood moon": Move("blood moon", "normal", "special", 140, 1.0, 5, None),
    "matcha gotcha": Move("matcha gotcha", "grass", "special", 80, 0.9, 15, None),
    "syrup bomb": Move("syrup bomb", "grass", "special", 60, 0.85, 10, {"target_stat": ["opponent", "speed"], "change": [-1]}),
    "ivy cudgel": Move("ivy cudgel", "grass", "physical", 100, 1.0, 10, None),
    "electro shot": Move("electro shot", "electric", "special", 130, 1.0, 10, {"target_stat": ["opponent", "special_attack"], "change": [+1]}),
    "tera starstorm": Move("tera starstorm", "normal", "special", 120, 1.0, 5, None),
    "fickle beam": Move("fickle beam", "dragon", "special", 80, 1.0, 5, None),
    "burning bulwark": Move("burning bulwark", "fire", "status", 0, 0.0, 10, None),
    "thunderclap": Move("thunderclap", "electric", "special", 70, 1.0, 5, None),
    "mighty cleave": Move("mighty cleave", "rock", "physical", 95, 1.0, 5, None),
    "tachyon cutter": Move("tachyon cutter", "steel", "special", 50, 0.0, 10, None),
    "hard press": Move("hard press", "steel", "physical", 0, 1.0, 10, None),
    "dragon cheer": Move("dragon cheer", "dragon", "status", 0, 0.0, 15, None),
    "alluring voice": Move("alluring voice", "fairy", "special", 80, 1.0, 10, None),
    "temper flare": Move("temper flare", "fire", "physical", 75, 1.0, 10, None),
    "supercell slam": Move("supercell slam", "electric", "physical", 100, 0.95, 15, None),
    "psychic noise": Move("psychic noise", "psychic", "special", 75, 1.0, 10, None),
    "upper hand": Move("upper hand", "fighting", "physical", 65, 1.0, 15, None),
    "malignant chain": Move("malignant chain", "poison", "special", 100, 1.0, 5, None),
}
